### ISSUE TITLE
The order of data returned by the server is NOT the same with the order of data sent by the client?

### ISSUE THREAD

**Issue by nrty** [hanxiao/bert-as-service#105]
There are 7207 lines in the input file 'query_title_sample_data'. With setting "max_batch_size=256",  the input file will be partitioned into small batches. But it seems that in the data returned by the server, the order of different batches are changed, compared with order of input file.
By the way, num_worker is 1.

Is this normal? or maybe I'm misunderstanding something about the C/S architecture?
Ideally it is expected that the order of data returned by the server is the same with the order of data sent by the client. Or is there anything can be done to achieve this?

code example:

    bc = BertClient()

    query_list = []
    title_list = []
    with open('query_title_sample_data', encoding = 'utf-8') as fp:
        for line in fp:
            values = line.strip("\n").split('\t')
            query_list.append(values[0])
            title_list.append(values[1])

    querys_vec = bc.encode(query_list)
    titles_vec = bc.encode(title_list)

    for i in range(0, len(querys_vec)):
        cosine_distance = np.dot(querys_vec[i], titles_vec[i]) /\
             (np.sqrt(np.dot(querys_vec[i], querys_vec[i])) * \
             np.sqrt(np.dot(titles_vec[i], titles_vec[i])))
        print(cosine_distance)

**Comment by hanxiao** [comment]
fixed in #101 and available since 1.4.6 please do `pip install -U bert-serving-server bert-serving-client`

**Comment by nrty** [comment]
check OK.
Thanks!
