### ISSUE TITLE
can I use 1024-hidden bert model?

### ISSUE THREAD

**Issue by thetuxedo** [hanxiao/bert-as-service#122]
* [X] Are you running the latest `bert-as-service`?
* [X] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [X] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#faq)?
* [X] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

Will the service be able to return vector of 1024 instead of 768, in case of using Bert-large model?

Thanks!

...

**Comment by hanxiao** [comment]
yes, for sure.  768-dim is just an example when using uncased BERT model.
