### ISSUE TITLE
Support Timeout for BertClient?

### ISSUE THREAD

**Issue by NekoApocalypse** [hanxiao/bert-as-service#134]
Currently, if no BERT server is running at appointed ip & port, `bc = BertClient()` hangs indefinitely.
Maybe add a timeout option?

**Comment by hanxiao** [comment]
will do

**Comment by hanxiao** [comment]
fyi, this feature was fixed in #136 and is available since 1.5.7, please do 
```bash
pip install -U bert-serving-server bert-serving-client
```

**Comment by NekoApocalypse** [comment]
Awesome. Keep up the good work.
