### ISSUE TITLE
Are there any example code of fine-tuning model for example5.py?

### ISSUE THREAD

**Issue by ruanwz** [hanxiao/bert-as-service#141]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [ x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

This project is very handy, and I want to make use of it quickly. I run example5, the result is poor when only using the original BERT model(chinese_L-12_H-768_A-12). Can you please share the fine tuning scripts for that dataset(https://github.com/thunlp/CAIL)? Thanks!

**Comment by hanxiao** [comment]
`example5.py` is a very simple toy example for showing how to use it with `tf.Estimator`, it's a starting point to guide you building more sophisticated models. That said, there are indeed many ways to improve `example5.py`, but that's not my priority now. Contributions are welcome.

For fine-tuning script, please refer to Google's [`run_classifier.py`](https://github.com/google-research/bert/blob/master/run_classifier.py).
For serving a fine-tuned model using `bert-as-service`, please follow https://github.com/hanxiao/bert-as-service#serving-a-fine-tuned-bert-model
