### ISSUE TITLE
Why the result is not good on the Dataset——2018CCFBDCI汽车行业用户观点主题及情感识别？

### ISSUE THREAD

**Issue by a414351664** [hanxiao/bert-as-service#145]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ ] Are you running the latest `bert-as-service`?
* [ ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):source 
- TensorFlow version:1.12.0
- Python version:3.6.7
- `bert-as-service` version: the former version，not the lastest
- GPU model and memory:10G
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
python app.py -pooling_strategy NONE -model_dir ./chinese_L-12_H-768_A-12/ -num_worker=1
```

and calling the server via:
```python
bc = BertClient()
x_= bc.encode(x_batch) # (batch_size, seq_len) and get x_(batch_size, seq_len, 768)
```

Then this issue shows up:
I have used the sentence embedding to the model—— text classification, just connected a DNN and a classifier to predict the label(such as price, power, space, security and so on) base on comment on cars.
But the result is very bad.
Then I used the word embedding to the RNN and softmax,is bad too.I do not know why.
...

**Comment by Colanim** [comment]
Do you have an implementation that works correctly ?

**Comment by hanxiao** [comment]
could you paste the command for starting the server?

**Comment by hanxiao** [comment]
could you fill in the issue form so that I can know which version of `bert-as-service` are you using?

**Comment by a414351664** [comment]
> could you fill in the issue form so that I can know which version of `bert-as-service` are you using?

OK，I have update the issue form.
If I fine tune the model,will it take a long time?
Thank you!

**Comment by hanxiao** [comment]
Before changing your model or doing fine-tuning, I **strongly suggest** you to use the latest `bert-as-service` and give a retry. Please do
```bash
pip install -U bert-serving-server bert-serving-client
```
Based on your server command and the form, I suspect you are using a pretty old version, which was even not installed via pip. Note that, there was some bugs in previous version, and was fixed [since 1.5.0](https://github.com/hanxiao/bert-as-service/releases?after=v1.5.2). These bugs may degrade the accuracy.

**Comment by a414351664** [comment]
> Before changing your model or doing fine-tuning, I **strongly suggest** you to use the latest `bert-as-service` and give a retry. Please do
> 
> ```shell
> pip install -U bert-serving-server bert-serving-client
> ```
> 
> Based on your server command and the form, I suspect you are using a pretty old version, which was even not installed via pip. Note that, there was some bugs in previous version, and was fixed [since 1.5.0](https://github.com/hanxiao/bert-as-service/releases?after=v1.5.2). These bugs may degrade the accuracy.

OK,thanks.I will try it.

**Comment by a414351664** [comment]
> Before changing your model or doing fine-tuning, I **strongly suggest** you to use the latest `bert-as-service` and give a retry. Please do
> 
> ```shell
> pip install -U bert-serving-server bert-serving-client
> ```
> 
> Based on your server command and the form, I suspect you are using a pretty old version, which was even not installed via pip. Note that, there was some bugs in previous version, and was fixed [since 1.5.0](https://github.com/hanxiao/bert-as-service/releases?after=v1.5.2). These bugs may degrade the accuracy.

**Comment by a414351664** [comment]
commond：
bert-serving-start -model_dir ./chinese_L-12_H-768_A-12/ -max_seq_len 128 -port 5557 -port_out 5558 -pooling_strategy REDUCE_MEAN -num_worker=1

but the package info：
(bert) pengwei@ubuntu:~/bert-as-service-master$ conda list

#packages in environment at /home/pengwei/.conda/envs/bert:
#Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl  
absl-py                   0.6.1                    py36_0  
astor                     0.7.1                    py36_0  
bert-serving-client       1.6.2                     <pip>
bert-serving-server       1.6.2                     <pip>
blas                      1.0                         mkl  

the return is：
AttributeError: version mismatch! server version is 1.5.7 but client version is 1.6.2!
consider "pip install -U bert-serving-server bert-serving-client"
or disable version-check by "BertClient(check_version=False)"

**Comment by hanxiao** [comment]
check your BertClient port, apparently you are connecting to an old (and living) 1.5.7 server.
