### ISSUE TITLE
when is the training of example 5 finished?

### ISSUE THREAD

**Issue by basque21** [hanxiao/bert-as-service#150]
**Prerequisites**

* [x ] Are you running the latest `bert-as-service`?
* [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**Comment by hanxiao** [comment]
it runs forever for demo purpose.
