### ISSUE TITLE
May I need to add <CLS> and <SEP> to my input?

### ISSUE THREAD

**Issue by ZhaoXiny** [hanxiao/bert-as-service#151]
hi,
When I input data to model, may I need to add <CLS> and <SEP> to text line? Or your code had already done so?
thx

**Comment by hanxiao** [comment]
absolute no need.

in fact, you can get embedding on the [CLS] [SEP] token if you like, see: https://github.com/hanxiao/bert-as-service#q-what-are-the-available-pooling-strategies

**Comment by yuchenlin** [comment]
what if I want to specific [sep] by myself for special tasks.

For example, I would like to make a QA pair become a sentence like `[CLS] question [sep] answer [sep]`. Is this possible?
