### ISSUE TITLE
Why the result is bad on sentence to document?

### ISSUE THREAD

**Issue by Gpwner** [hanxiao/bert-as-service#153]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

### Description

When I am matching a sentence to doc,I found the result is not so good.I  choose the model：cased_L-24_H-1024_A-16.

Is this because I  choose the wrong model？

Here is my step:
①encode a sentence to a vector(let's say vectorA);
②encode a document to a vector(let's say vectorB);
③cal the Similarity of vectorA and VectorB

here is my Similarity cal function:

```
def cos(vector_a, vector_b):
     vector_a = np.mat(vector_a)
    vector_b = np.mat(vector_b)
    num = float(vector_a * vector_b.T)
    denom = np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
    cos = num / denom
    return cos
```

**Comment by hanxiao** [comment]
apparently you didn't read faq and search for past issues. there is no point to ask same question again, saving time for both of us.

https://github.com/hanxiao/bert-as-service#q-the-cosine-similarity-of-two-sentence-vectors-is-unreasonably-high-eg-always--08-whats-wrong

#132 #30
