### ISSUE TITLE
I can't proceed the server after 'freeze' stage. 

### ISSUE THREAD

**Issue by shkevinlee** [hanxiao/bert-as-service#160]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [O] Are you running the latest `bert-as-service`?
* [O] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [O] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and DistributionL  Linux Ubuntu 16.04)
- TensorFlow installed from (source or binary):
- TensorFlow version: 1.12
- Python version: 3.6.7
- `bert-as-service` version:  1.6.4
- GPU model and memory: X
- CPU model and memory: O, 16G

---

### Description
Sever seems not work after this log...
![screenshot from 2018-12-24 19-44-33](https://user-images.githubusercontent.com/17266924/50411396-79c56c80-07b4-11e9-9641-cff25e0c5b1d.png)

It doesn't seem to use memory, and It doens't work after even I wait some hours.
What should I do?

**Comment by hanxiao** [comment]
the whole graph optimization should be done in at most 1 minute. Seems that something wrong at `graph.py:124`. Did you modify the `cased_L...` model or is it the original pretrained model released by Google?

**Comment by shkevinlee** [comment]
I don't know why this error cause, but i re-install ubuntu and virtual env , then it works! 
Anyway, thanks for your awesome works.

**Comment by hanxiao** [comment]
hmm, weird. but glad to hear that! close
