### ISSUE TITLE
Why use another process to optimize the graph?

### ISSUE THREAD

**Issue by tyxr** [hanxiao/bert-as-service#161]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

 with Pool(processes=1) as pool:
 # optimize the graph, must be done in another process
 from .graph import optimize_graph
 self.graph_path = pool.apply(optimize_graph, (self.args,))
 # from .graph import optimize_graph
# self.graph_path = optimize_graph(self.args, self.logger)

...

**Comment by hanxiao** [comment]
nice that you notice this. 

I've tried the simple way. However, there will be some weird side-effect when the `BertServer` calls tensorflow and then start the `BertWorker` (which calls tensorflow again). 

One example I remember is once `tf.ConfigProto(device_count={'GPU': 0})` is set in the process of `BertServer`, the worker won't be able to find any GPU how ever you config `tf.ConfigProto` in its own process, sometimes the worker is just hanging there forever. Seems that some environment variables are unexpectedly inherited from `BertServer` and affect `BertWorker`.

That said, the best way to work with tensorflow in multi-process environment is make a strict separation (starting from `import tensorflow as tf`). It saves a lot of troubles.

Reference: 
- Checkout my old blog post mentioned this issue: https://hanxiao.github.io/2017/07/07/Get-10x-Speedup-in-Tensorflow-Multi-Task-Learning-using-Python-Multiprocessing/#using-tensorflow-for-preprocessing-in-subprocess
- this issue: https://github.com/tensorflow/tensorflow/issues/8220

**Comment by tyxr** [comment]
Thank you for your answer.
