### ISSUE TITLE
graph optimization fail

### ISSUE THREAD

**Issue by chiyuzhang94** [hanxiao/bert-as-service#163]
This issue shows up:
I can successfully use this application on my MacBook. Then, I tried to apply it on a cloud server, but it cannot work and return error: FileNotFoundError: graph optimization fails and returns empty result. Could you please help me to figure out this issue? Thanks!
...

**Comment by hanxiao** [comment]
@chiyuzhang94 is this issue still there?

**Comment by chiyuzhang94** [comment]
> @chiyuzhang94 is this issue still there?

Hi Han, Thanks for your attention and sorry for the inconveniences. It still doesn't work. I am using a virtual environment with python 3.6 on a cloud server and version 1.6.4 for bert-serving-server. I unzipped BERT-Large, Uncased in a fold call "uncased_L-24_H-1024_A-16", and created a shell file bert-server.sh : `#!/bin/bash
bert-serving-start  -model_dir ~/py3.6/uncased_L-24_H-1024_A-16 -num_worker=8 
`
Then, I used salloc to run this job: `salloc --time=10:0:0 --ntasks=1 --cpus-per-task=8 --mem=16G --gres=gpu:1 --account=***** --job-name=bert-server srun $VIRTUAL_ENV/bert-server.sh`

Finally, the termial return such errors:
![screen shot 2018-12-26 at 7 07 28 pm](https://user-images.githubusercontent.com/33407613/50463588-83c8a600-0941-11e9-87ec-4c28c251ae2b.png)

**Comment by chiyuzhang94** [comment]
> @chiyuzhang94
> I met this problem when I try `BERT-Base, Chinese` and sovled it by redownload the pretrained model. Maybe your file is broken, have a MD5 check could help.
Thanks, I tried to use other models, it still didn't work. But any model can work on my local computer.

**Comment by saravananpsg** [comment]
@hanxiao Thank you for the repo. 

Even I had the same issue however when I re-downloaded the recommended pre-trained model, I solved this error. Not sure why it occurred in the first place. Also, I have increased the number of workers to 8

bert-serving-start -model_dir /tmp/multi_cased_L-12_H-768_A-12 -num_worker=8

**Comment by hanxiao** [comment]
Could you please double check the python version on the cloud server? I found this line is particular suspicious.
```
invalid syntax (<string>, line 28)
``` 

which points to this place:
https://github.com/hanxiao/bert-as-service/blob/5e5bad07911dc44fd959dec75d7fb56bc7ac5f53/server/bert_serving/server/graph.py#L28-L30
This often indicates a wrong python version (2 instead of 3, or some other versions that don't appreciate `@staticmethod` in `Enum`); or some random typos in the code. We can rule out the latter if you are installing `bert-serving-server` via pip. But that said, if you are using py2, the server shouldn't be able to start in the first place.

**Comment by hanxiao** [comment]
@saravananpsg hmm, strange. I will add more logging there and print the full error traceback in the next version.

**Comment by chiyuzhang94** [comment]
> Could you please double check the python version on the cloud server? I found this line is particular suspicious.
> 
> ```
> invalid syntax (<string>, line 28)
> ```
> which points to this place:
> [bert-as-service/server/bert_serving/server/graph.py](https://github.com/hanxiao/bert-as-service/blob/5e5bad07911dc44fd959dec75d7fb56bc7ac5f53/server/bert_serving/server/graph.py#L28-L30)
> 
> Lines 28 to 30 in [5e5bad0](/hanxiao/bert-as-service/commit/5e5bad07911dc44fd959dec75d7fb56bc7ac5f53)
> 
>  @staticmethod 
>  def from_string(s): 
>      try: 
> 
> This often indicates a wrong python version (2 instead of 3, or some other versions that don't appreciate `@staticmethod` in `Enum`); or some random typos in the code. We can rule out the latter if you are installing `bert-serving-server` via pip. But that said, if you are using py2, the server shouldn't be able to start in the first place.

I checked my python version is 3.6.3.

**Comment by chiyuzhang94** [comment]
Thanks! I updated the modules and tried again. Here is the error report. 
![1227](https://user-images.githubusercontent.com/33407613/50491685-67bc1780-09c8-11e9-9efe-07a1d4a23275.png)

**Comment by hanxiao** [comment]
Thanks gotcha. Now I see the `invalid syntax` is raised from `single_image_random_dot_sterograms` not from `bert_as_service`. After googling, I found it's a tensorflow problem, and [this issue](https://github.com/tensorflow/tensorflow/issues/21164) as well as [this PR](https://github.com/tensorflow/tensorflow/pull/22044) discussed and addressed the exact problem.

You may follow the instruction in those threads or google the solution by yourself, or post issue to the tensorflow repo.

I'm closing this issue as it's unrelated to `bert-as-service`.

**Comment by chiyuzhang94** [comment]
> Thanks gotcha. Now I see the `invalid syntax` is raised from `single_image_random_dot_sterograms` not from `bert_as_service`. After googling, I found it's a tensorflow problem, and [this issue](https://github.com/tensorflow/tensorflow/issues/21164) as well as [this PR](https://github.com/tensorflow/tensorflow/pull/22044) discussed and addressed the exact problem.
> 
> You may follow the instruction in those threads or google the solution by yourself, or post issue to the tensorflow repo.
> 
> I'm closing this issue as it's unrelated to `bert-as-service`.

Sure. Thanks!

**Comment by PaulZhangIsing** [comment]
> > Thanks gotcha. Now I see the `invalid syntax` is raised from `single_image_random_dot_sterograms` not from `bert_as_service`. After googling, I found it's a tensorflow problem, and [this issue](https://github.com/tensorflow/tensorflow/issues/21164) as well as [this PR](https://github.com/tensorflow/tensorflow/pull/22044) discussed and addressed the exact problem.
> > You may follow the instruction in those threads or google the solution by yourself, or post issue to the tensorflow repo.
> > I'm closing this issue as it's unrelated to `bert-as-service`.
> 
> Sure. Thanks!

so may I know how did u manage to solve this issue??

**Comment by chenbaicheng** [comment]
@chiyuzhang94   which version of tensorflow are you using?

**Comment by chiyuzhang94** [comment]
> @chiyuzhang94 which version of tensorflow are you using?

I am using Version: 1.12.0+{cloud service name}, but I think it is a special version for the cloud service.

**Comment by w6688j** [comment]
How is this problem solved?
![image](https://user-images.githubusercontent.com/16603643/51464345-4d474500-1da0-11e9-9886-736703ff82b4.png)

**Comment by brandonchow1997** [comment]
> How is this problem solved?
> ![image](https://user-images.githubusercontent.com/16603643/51464345-4d474500-1da0-11e9-9886-736703ff82b4.png)

I got the same problem...Wondering how to solve it??

**Comment by hanxiao** [comment]
@w6688j @brandonchow1997  look at the error traceback, you can see that the `MemoryError` is thrown from tensorflow. So it's highly likely a tensorflow problem.

**Comment by chenbaicheng** [comment]
@hanxiao   can give a advice  ？  which  tensorflow  version   can use for this project。。。thanks

**Comment by hanxiao** [comment]
requirements are already written in README

chenbaicheng <notifications@github.com>于2019年1月24日 周四下午8:48写道：
