### ISSUE TITLE
how to get fine_tune model output probability

### ISSUE THREAD

**Issue by policeme** [hanxiao/bert-as-service#165]
hi, I have a problem, when i finish bert fine tune model of run_classifier.py, I use it to my task, but i don't know how to get probability of fine tune model.
when I use below code,  I get not same result when I feed same text_a and text_b, Please help me! Thanks!
![image](https://user-images.githubusercontent.com/30991932/50536706-20818280-0b92-11e9-9978-8c353260bbc3.png)

**Comment by policeme** [comment]
@hanxiao @jacobdevlin-google

**Comment by hanxiao** [comment]
close, unrelated to bert-as-service. note that this a place for reporting issues related to this repo only.
