### ISSUE TITLE
Does bert-as-service support Korean sentence?

### ISSUE THREAD

**Issue by hairzooc** [hanxiao/bert-as-service#168]
Hi,
I've found something weird when I enter Korean sentence as an input.

['아버지의 가방']
[[[ 0.34601828  0.3036006  -0.3474255  ...  0.60383546  1.122026
    0.18283758]
  [-0.16301844  0.3405585  -0.5474659  ...  1.3288096   1.2228076
    0.630607  ]
  [-0.17323802  0.2778925  -0.6195924  ...  1.1313229   1.3720961
    0.41921428]
  [ 0.31519005  0.2437449  -0.07339257 ...  0.2584101   1.2595382
    0.32994625]]]
['밥 먹었다']
[[[ 0.34601828  0.3036006  -0.3474255  ...  0.60383546  1.122026
    0.18283758]
  [-0.16301844  0.3405585  -0.5474659  ...  1.3288096   1.2228076
    0.630607  ]
  [-0.17323802  0.2778925  -0.6195924  ...  1.1313229   1.3720961
    0.41921428]
  [ 0.31519005  0.2437449  -0.07339257 ...  0.2584101   1.2595382
    0.32994625]]]

As you can see, even if I enter different sentence, I got same output.
And it turns out that if I enter another sentence which is consisted of 2 word (one blank space between 2 word), I got same output as well. (eg. '안녕 친구들' and '거기 멈춰')
As long as I know, BERT support multilingual including Korean.
Is there anything I missed?
Please let me know if you have some idea on this issue. Thank you.

**Comment by hanxiao** [comment]
yes, it supports Korean, but only if you are using [BERT-Base, Multilingual Cased (New)](https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip). Otherwise all Korean tokens will be considered as `<UNK>`, which explains your observation.

**Comment by harry81** [comment]
**Bert base**
```shell
 $ ls -al multi_cased_L-12_H-768_A-12
total 684M
-rw-r--r-- 1 hm-kono hm-kono  521 11월 24  2018 bert_config.json
-rw-r--r-- 1 hm-kono hm-kono 682M 11월 24  2018 bert_model.ckpt.data-00000-of-00001
-rw-r--r-- 1 hm-kono hm-kono 8.5K 11월 24  2018 bert_model.ckpt.index
-rw-r--r-- 1 hm-kono hm-kono 888K 11월 24  2018 bert_model.ckpt.meta
-rw-r--r-- 1 hm-kono hm-kono 973K 11월 24  2018 vocab.txt
```

**How I run bert server**
```shell 
$ bert-serving-start -model_dir ../bert/models/multi_cased_L-12_H-768_A-12 -num_worker=1 -show_tokens_to_client
```

**Client**
```python
In [53]: bc.encode(['아버지의 가방'], show_tokens=True)[1]
Out[53]: [['[CLS]', '[UNK]', '[UNK]', '[SEP]']]

In [55]: bc.encode(['你最近怎麼樣'], show_tokens=True)[1]
Out[55]: [['[CLS]', '你', '最', '近', '怎', '麼', '樣', '[SEP]']]
```
Could you have time to look at this? 
Recognizing Chineese text looks fine but not Korean text.

**Comment by harry81** [comment]
After adding ```-cased_tokenization``` when starting `bert-serving-start`, it seems to work.

```python
In [77]: bc.encode(['아버지의 가방'], show_tokens=True)[1]
Out[77]: [['[CLS]', '아버지', '##의', '가', '##방', '[SEP]']]
```
