### ISSUE TITLE
Data used in example4

### ISSUE THREAD

**Issue by PaulZhangIsing** [hanxiao/bert-as-service#172]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x]  Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):pip it
- TensorFlow version: 1.12.0 GPU
- Python version: 3.6.7
- `bert-as-service` version: 
- GPU model and memory: GeForce GTX TITANS * 4
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```bash
python example4.py
```

Then this issue shows up:
```bash
NotFoundError (see above for traceback): /data/cips/data/lab/data/dataset/final_all_data/exercise_contest/data_train.json; No such file or directory
	 [[node IteratorGetNext (defined at example4.py:47)  = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
```

I did not find any data described in the codes, if I want to run the example, shall I use my own data instead.
If that is the case, how should I preprocess data (i.e. in what format so that I could utilize the code)

**Comment by hanxiao** [comment]
`example4.py` and `example5.py` use the same data, which can be downloaded from here: https://github.com/thunlp/CAIL/blob/master/README_en.md#23-dataset-download

You will see the same directory structure after decompress it
