### ISSUE TITLE
Example4 is unable to run smoothly, seems some codes need to be added.

### ISSUE THREAD

**Issue by PaulZhangIsing** [hanxiao/bert-as-service#178]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):

    OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
    TensorFlow installed from (source or binary):pip it
    TensorFlow version: 1.12.0 GPU
    Python version: 3.6.7
    bert-as-service version:
    GPU model and memory: GeForce GTX TITANS * 4
    CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
python example4.py
```

Then this issue shows up:

```bash
OutOfRangeError (see above for traceback): End of sequence
	 [[node IteratorGetNext (defined at Bert_server_used.py:36)  = IteratorGetNext[output_shapes=[<unknown>, <unknown>], output_types=[DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
```
and then if I add range, making it equal to the length of train_fp after first lam, the following would occur
```bash
TypeError: <lambda>() missing 1 required positional argument: 'y'
```
...

**Comment by hanxiao** [comment]
hmm, will check

**Comment by hanxiao** [comment]
I can't reproduce the error. Maybe it's your JSON file problem. I tested with https://cail.oss-cn-qingdao.aliyuncs.com/cail2018_small_0518.tar.gz and it's no problem.

**Comment by PaulZhangIsing** [comment]
thanks shall try again

Sent from my iPhone

On 14 Jan 2019, at 11:49, Han Xiao <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce the error. Maybe it's your JSON file problem. I tested with https://cail.oss-cn-qingdao.aliyuncs.com/cail2018_small_0518.tar.gz and it's no problem.
