### ISSUE TITLE
entrypoint.sh issue in docker run

### ISSUE THREAD

**Issue by gitathrun** [hanxiao/bert-as-service#180]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`? I installed 1.6.6
* [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`? I use the files in the Docker directory
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)? Docker usage slightly different
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description
Hi, hanxiao
I am trying to get the docker uprunning on a remote GPU virtual machine, with the dockerfile and entrypoint.sh in your repo, but it encountered with following issue:

```
azureuser@xxxx:~$ sudo docker run -it --rm -p xx -p xx --runtime=nvidia -t bert-as-service-base

  from ._conv import register_converters as _register_converters
usage: bert-serving-start [-h] -model_dir MODEL_DIR
                          [-tuned_model_dir TUNED_MODEL_DIR]
                          [-ckpt_name CKPT_NAME] [-config_name CONFIG_NAME]
                          [-max_seq_len MAX_SEQ_LEN]
                          [-pooling_layer POOLING_LAYER [POOLING_LAYER ...]]
                          [-pooling_strategy {NONE,REDUCE_MAX,REDUCE_MEAN,REDUCE_MEAN_MAX,FIRST_TOKEN,LAST_TOKEN}]
                          [-mask_cls_sep] [-port PORT] [-port_out PORT_OUT]
                          [-num_worker NUM_WORKER]
                          [-max_batch_size MAX_BATCH_SIZE]
                          [-priority_batch_size PRIORITY_BATCH_SIZE] [-cpu]
                          [-xla] [-gpu_memory_fraction GPU_MEMORY_FRACTION]
                          [-device_map DEVICE_MAP [DEVICE_MAP ...]]
                          [-prefetch_size PREFETCH_SIZE] [-verbose] [-version]
bert-serving-start: error: argument -num_worker: invalid int value: ''
```

Then I changed the code in entrypoint.sh
```
#!/bin/sh
bert-serving-start -num_worker=**$1** -model_dir /model
```
into
```
#!/bin/sh
bert-serving-start -num_worker=**1** -model_dir /model
```

then it worked, at least on my machine, 
```
usage: /usr/local/bin/bert-serving-start -num_worker=1 -model_dir /model
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                 cpu = False
          device_map = []
 gpu_memory_fraction = 0.5
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /app/bert_model
          num_worker = 1
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
     tuned_model_dir = None
             verbose = False
                 xla = False
```

Would you mind to test this change?

Many thanks.

**Comment by hanxiao** [comment]
`-num_worker=$1` means taking first argument of `entrypoint.sh` as number of workers, whereas `-num_worker=1` means single worker only.

**Comment by gitathrun** [comment]
> `-num_worker=$1` means taking first argument of `entrypoint.sh` as number of workers, whereas `-num_worker=1` means single worker only.

So the $NUM_WORKERS must be valued before using it according to your README.md, I think?
```
NUM_WORKER=1
docker run --runtime nvidia -dit -p 5555:5555 -p 5556:5556 -v $PATH_MODEL:/model -t bert-as-service $NUM_WORKER
```

Otherwise, use 1 instead of $1?

**Comment by hanxiao** [comment]
you can set num_worker according to the resources you have, doesn’t have to be one.

Feel free to change entrypoint.sh, it’s just an example.
