### ISSUE TITLE
'bert-serving-start' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by sailormoon2016** [hanxiao/bert-as-service#194]
Hi, 
This is a very silly question.....
I have python 3.6.6, tensorflow 1.12.0, doing everything in conda environment, Windows 10.
I pip installed bert-serving-server/client and it shows 
`Successfully installed GPUtil-1.4.0 bert-serving-client-1.7.2 bert-serving-server-1.7.2 pyzmq-17.1.2`
but when I run the following as CLI
`bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12/ -num_worker=4`
it says
`'bert-serving-start' is not recognized as an internal or external command`

I found bert-serving library is located under C:\Users\Name\Anaconda\Lib\site-packages. So I tried to run bert-serving-start again under these three folders:
1. site-packages
2. site-packages\bert_serving
3. site-packages\bert_serving_server-1.7.2.dist-info

![](http://i67.tinypic.com/4ke788.png)
However, the result is same as not recognized. Can anyone help me?

**Comment by Colanim** [comment]
Did you try adding `site-packages\bert_serving` to your `PATH` variable ?

**Comment by hanxiao** [comment]
@sailormoon2016 please refer to the step 1 of https://github.com/hanxiao/bert-as-service/issues/99#issuecomment-452769280

for the latest `bert-as-service` >=1.7.0, you don't need to do step 2 in that comment

**Comment by hanxiao** [comment]
fyi, this is fixed in #212, the new feature is available since 1.7.7. Please do 
```bash
pip install -U bert-serving-server bert-serving-client
```
for the update.

**Comment by A6Matrix** [comment]
> Hi,
> This is a very silly question.....
> I have python 3.6.6, tensorflow 1.12.0, doing everything in conda environment, Windows 10.
> I pip installed bert-serving-server/client and it shows
> `Successfully installed GPUtil-1.4.0 bert-serving-client-1.7.2 bert-serving-server-1.7.2 pyzmq-17.1.2`
> but when I run the following as CLI
> `bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12/ -num_worker=4`
> it says
> `'bert-serving-start' is not recognized as an internal or external command`
> 
> I found bert-serving library is located under C:\Users\Name\Anaconda\Lib\site-packages. So I tried to run bert-serving-start again under these three folders:
> 
> 1. site-packages
> 2. site-packages\bert_serving
> 3. site-packages\bert_serving_server-1.7.2.dist-info
> 
> ![](https://camo.githubusercontent.com/e6c8298aa0016697dd6dbfc0ff02565bb9278d0b/687474703a2f2f6936372e74696e797069632e636f6d2f346b653738382e706e67)
> However, the result is same as not recognized. Can anyone help me?

excuse me , how  to run bert-serving-start nder these  folders?

**Comment by hanxiao** [comment]
@A6Matrix version too old, please do `pip install -U` first

**Comment by A6Matrix** [comment]
> @A6Matrix version too old, please do `pip install -U` first

I have updated the latest version
![image](https://user-images.githubusercontent.com/18898570/55527209-9b46c600-56ca-11e9-9018-e0e2780f0e42.png)
 i don't know how to run bert-serving-start under these folders, because I also encountered a problem that 'bert-serving-start' could not be recognized, i don't know how to solve it

**Comment by A6Matrix** [comment]
> @A6Matrix version too old, please do `pip install -U` first

My system is a Windows system and my Python version is 3.5，tensorflow 1.9.0，so how to run bert-serving-start and start service？

**Comment by Okarango-Data-Technologies** [comment]
Stop writing shitty answers and give a solution which actually solves the problem. In my case, I don't have any executables with the name bert-serving-start.

**Comment by AsKayDevs** [comment]
Stop writing shitty answers and give a solution which actually solves the problem. In my case, I don't have any executables with the name bert-serving-start.

**Comment by monk1337** [comment]
Create a start-bert-as-service.py with the following code

```
import sys

from bert_serving.server import BertServer
from bert_serving.server.helper import get_run_args


if __name__ == '__main__':
    args = get_run_args()
    server = BertServer(args)
    server.start()
    server.join()
```


so you can run with the following command
python start-bert-as-service.py -model_dir ./tmp/chinese_L-12_H-768_A-12/ -num_worker=1

**Comment by amitgupta911** [comment]
> Create a start-bert-as-service.py with the following code
> 
> ```
> import sys
> 
> from bert_serving.server import BertServer
> from bert_serving.server.helper import get_run_args
> 
> 
> if __name__ == '__main__':
>     args = get_run_args()
>     server = BertServer(args)
>     server.start()
>     server.join()
> ```
> 
> so you can run with the following command
> python start-bert-as-service.py -model_dir ./tmp/chinese_L-12_H-768_A-12/ -num_worker=1

@monk1337  Getting this Error using this solution on windows 10 with python 3.6 and tensorflow 2.0.0 .
![image](https://user-images.githubusercontent.com/51500641/68836264-f2d8f580-06df-11ea-93e9-686bfb4fc7a2.png)

**Comment by Giuli17G** [comment]
Hi,
I had another problem...
I installed correctly bert-serving-server and bert-serving client and I downloaded the multilingual model that I uncompressed in the same folder on my code.
But when i run
bert-serving-start -model_dir /tmp/multi_cased_L-12_H-768_A-12/ -num_worker=1
it launches the following error:
SyntaxError: invalid token.
Could you help me?
Thank you so much

**Comment by hanxiao** [comment]
> Stop writing shitty answers and give a solution which actually solves the problem. In my case, I don't have any executables with the name bert-serving-start.

@askaydevs You should be really shamed of yourself!

**Comment by askaydevs** [comment]
@hanxiao My sincere apologies for that earlier comment. I was just starting with BERT and at that moment there were not enough resources to learn to learn about BERT and also I was an amateur, after giving numerous unsuccessful tries I got frustrated and wrote that; didn't mean any of that. I totally understand you are doing exceptional job to keep things clean and bug free. Again I am sorry @hanxiao.

**Comment by hanxiao** [comment]
![image](https://user-images.githubusercontent.com/2041322/81619470-f678db00-93e9-11ea-9ce1-2352ee3d6335.png)
