### ISSUE TITLE
E:GRAPHOPT:[gra:opt:139]:fail to optimize the graph!

### ISSUE THREAD

**Issue by HannahXu** [hanxiao/bert-as-service#195]
[**Prerequisites**]

> Please fill in by replacing `[ ]` with `[x]`.

* [√ ] Are you running the latest `bert-as-service`?
* [√ ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ √] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [√ ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution :Linux mobaXterm
- TensorFlow installed from (source or binary):pip install tensorflow-gpu  & pip install --upgrade tensorflow-gpu

- TensorFlow version:1.12
- Python version:3.6
- `bert-as-service` version: pip install -U 
- GPU model and memory:
![image](https://user-images.githubusercontent.com/37390613/51291010-9c0f7a80-1a40-11e9-9803-261c0bba14e0.png)
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```
bert-serving-start -model_dir /tmp/chinese_L-12_H-768_A-12/ -num_worker=4  

![image](https://user-images.githubusercontent.com/37390613/51291222-6028e500-1a41-11e9-8b1f-b2a3a0b643ec.png)

Then this issue shows up:
![image](https://user-images.githubusercontent.com/37390613/51291034-b9dcdf80-1a40-11e9-9396-7d37414257ca.png)

![image](https://user-images.githubusercontent.com/37390613/51291023-acbff080-1a40-11e9-8ae8-9ee110020f48.png)

...

**Comment by hanxiao** [comment]
looks like your model config `/tmp/chinese_L-12_H-768_a-12/bert_config.json` is not found? could you double check that?

**Comment by HannahXu** [comment]
Please look at the third last figure, there is a bert_config.json file in the folder.

**Comment by hanxiao** [comment]
but isn't your picture indicating `xx/bert/tmp/chinese_L-12_H-768_A-12/`? 

![image](https://user-images.githubusercontent.com/2041322/51294197-db43c880-1a4c-11e9-889a-9984377005ed.png)

could you `cd` to the folder in which json config located, and then type `pwd` there?

**Comment by policeme** [comment]
@hanxiao i have same issue

**Comment by policeme** [comment]
![image](https://user-images.githubusercontent.com/30991932/51294463-e9461900-1a4d-11e9-80bd-44e31f12f597.png)

**Comment by policeme** [comment]
@hanxiao  this is my config, i set absolute path

**Comment by HannahXu** [comment]
![image](https://user-images.githubusercontent.com/37390613/51294608-a46eb200-1a4e-11e9-8d59-5b5ac23e5132.png)

**Comment by HannahXu** [comment]
![image](https://user-images.githubusercontent.com/37390613/51294641-d253f680-1a4e-11e9-8d4a-a0c0c0213fca.png)

**Comment by hanxiao** [comment]
@HannahXu see now you have the absolute path, copy paste as `-model_dir`

**Comment by HannahXu** [comment]
solved 
thanks!

**Comment by hanxiao** [comment]
@policeme there is **absolutely** no reason to hard-code the path in the source. Why can't you use CLI `-model_dir` etc.?

This is not a bug of this repo. It's basic Linux/Windows usage. Closed.
