### ISSUE TITLE
Attribute error on Numpy 1.16

### ISSUE THREAD

**Issue by mayank408** [hanxiao/bert-as-service#201]
* [x] Are you running the latest `bert-as-service`?
* [X] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [X] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [X] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

Attribute Error coming up while working with the Latest Numpy version 1.16
![screenshot 2019-01-18 at 12 10 09 pm](https://user-images.githubusercontent.com/22056321/51369659-676ff180-1b1a-11e9-81dd-34b9bd67fe75.png)
Running fine on version 1.15 or lesser

**Comment by hanxiao** [comment]
from the traceback you can see that the error is thrown from `numpy`, not relevant to this repo.

**Comment by mayank408** [comment]
Sure Thanks @hanxiao
