### ISSUE TITLE
trouble running example8.py

### ISSUE THREAD

**Issue by nyck33** [hanxiao/bert-as-service#205]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): binary 
- TensorFlow version: 1.12.0
- Python version: Python 3.6.5 :: Anaconda custom (64-bit)

- `bert-as-service` version:   whatever these commands gave me
```
pip install bert-serving-server  # server
pip install bert-serving-client  # client, independent of `bert-serving-server`

```
- GPU model and memory:  compute capability 2.1 Nvidia NVS-4200M (no Cuda or Cudnn available)
- CPU model and memory: Intel i3 and 8GB DDR3

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir /media/nobu/"Ubuntu Backup"/"Comp Sci"/_DeepLearning/NLP/multi_cased_L-12_H-768_A-12/ -cpu -max_batch_size 16 -num_worker=1
```

and calling the server via:
```python
bc = BertClient(port=4000, port_out=4001)
bc.encode(questions)
```

Then this issue shows up:

This is for example8.py, ie. Building a QA semantic search engine in 3 minutes, it's hanging at:

```
35 questions loaded, avg. len of 9
>>> bc = BertClient(port=4000, port_out=4001)
```

I could do the Use Client to Get Sentence Encodes example and also when I call the server with just 
```
bc=BertClient()
bc.encode(questions)
```
I get the `your question` prompt but regardless of what I type, I seem to get the same five suggestions.  

Please see comments below.
...

**Comment by nyck33** [comment]
I guess the ports are for when you are connecting remotely to the bert server from a client and finally I'm guessing because this is a 3 minute example that the accuracy is not that good.

**Comment by nyck33** [comment]
After changing the ports to reflect that I have both server and client locally:

```
bc = BertClient(port=5555, port_out=5556)
doc_vecs = bc.encode(questions)

```
My results are so bad, I basically get the same suggestions for every question:

```
your question: what is the best pooling?
top 5 questions similar to "what is the best pooling?"
> 995.9	What is backend based on?
> 948.8	What are the available pooling strategies?
> 937.1	Could I use other pooling techniques?
> 932.5	What is the parallel processing model behind the scene?
> 908.7	Why does the server need two ports?
your question: is there Chinese support?
top 5 questions similar to "is there Chinese support?"
> 923.0	What is backend based on?
> 885.2	Could I use other pooling techniques?
> 867.2	What is the parallel processing model behind the scene?
> 864.7	What are the available pooling strategies?
> 851.3	Why does the server need two ports?
your question: does it support chinese
top 5 questions similar to "does it support chinese"
> 924.8	What is backend based on?
> 905.3	Could I use other pooling techniques?
> 865.1	Why does the server need two ports?
> 861.0	What are the available pooling strategies?
> 860.8	What is the parallel processing model behind the scene?
your question: what is the best pooling strategy?
top 5 questions similar to "what is the best pooling strategy?"
> 967.8	What is backend based on?
> 939.5	What are the available pooling strategies?
> 921.3	Could I use other pooling techniques?
> 918.9	What is the parallel processing model behind the scene?
> 892.0	Why does the server need two ports?
your question: 

```

**Comment by nyck33** [comment]
I think there is something happening with identifying questions because I get 35 questions and maybe that is skewing my results somehow?

```
nobu@nobu-ThinkPad-T420 ~ $ python
Python 3.6.5 |Anaconda custom (64-bit)| (default, Mar 29 2018, 18:21:58) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from bert_serving.client import BertClient
>>> from termcolor import colored
>>> 
>>> prefix_q = '##### **Q:** '
>>> topk = 5
>>> 
>>> with open('README.md') as fp:
...     questions = [v.replace(prefix_q, '').strip() for v in fp if v.strip() and v.startswith(prefix_q)]
...     print('%d questions loaded, avg. len of %d' % (len(questions), np.mean([len(d.split()) for d in questions])))
... 
35 questions loaded, avg. len of 9
>>> 

```

**Comment by nyck33** [comment]
Is this because I'm using the multilingual version of BERT?

**Comment by hanxiao** [comment]
you are using the wrong model. `example8.py` is reproducible with `uncased_L-12_H-768_A-12` whereas you are using `multi_cased_L-12_H-768_A-12`. The latter is trained on character-level for maximizing its compatibility on multi-lingual, thus doesn't understand English very well.

**Comment by bcbcbcbcbcl** [comment]
> 5556

What does port=5555, port_out=5556 mean? Do you have any reference? Thanks in advance!

**Comment by boxabirds** [comment]
> > 5556
> 
> What does port=5555, port_out=5556 mean? Do you have any reference? Thanks in advance!

The server architecture used by `bert-as-a-service` is asynchronous. They are the port numbers for the inbound request and the outbound response back to the client.
