### ISSUE TITLE
On Windows: FileNotFoundError: graph optimization fails and returns empty result

### ISSUE THREAD

**Issue by jacky7788** [hanxiao/bert-as-service#207]
**Prerequisites**
* [x ] Are you running the latest `bert-as-service`?
* [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

- TensorFlow version:1.12.0
- Python version:3.6.5

I'm using this command to start the server:
```bash
python bert-serving-start -model_dir=../../pre-trained-model/
```

Then this issue shows up:
![image](https://user-images.githubusercontent.com/28256291/51437775-c5990200-1cdd-11e9-8d40-b8deda283b50.png)

**Comment by davidlenz** [comment]
I had the same issue (Win 10).  What fixed it for me was to comment out two lines of logger code in the `/server/graph.py` file.

```
logger.info("freezing %d variables...", len(returned_variables))

logger.info("Converted %d variables to const ops.", how_many_converted) 
```

**Comment by jacky7788** [comment]
My version is 1.7.5

**Comment by jacky7788** [comment]
@davidlenz it works! thx!

**Comment by aloosley** [comment]
I also have the same issue,

- Windows 10
- tf version 1.12.0 (conda tensorflow-gpu venv)
- Same issue with and without `-cpu` flag
- Python version 3.6.8
- `bert-serving-start -version` gives: 1.7.4, upgraded now to 1.7.5 but the result is the same.

**Comment by hanxiao** [comment]
Somehow my logger mysteriously fails on Windows for this *particular* part. I did a quick fix, could you please give a try on 1.7.6 using `pip install -U`?

**Comment by aloosley** [comment]
@hanxiao, thanks for the update.  Unfortunately I get the same error with `1.7.6`, and it is again fixed by commenting out the logger lines 194 and 248 in `graph.py`.

**Comment by hanxiao** [comment]
🤦‍♂️

**Comment by willysys** [comment]
I also got this problem. My version is 1.7.6, os is win7 .

**Comment by hanxiao** [comment]
fyi, this is fixed in #212, the new feature is available since 1.7.7. Please do 
```bash
pip install -U bert-serving-server bert-serving-client
```
for the update.

**Comment by Constant-TL** [comment]
I encountered this problem again in version 1.8.0.

**Comment by 1357810la** [comment]
> 我遇到了同样的问题（Win 10）。为我修复它的方法是注释掉文件中的两行记录器代码。`/server/graph.py`
> 
> ```
> logger.info("freezing %d variables...", len(returned_variables))
> 
> logger.info("Converted %d variables to const ops.", how_many_converted) 
> ```
你好，请问你这个问题解决了吗

**Comment by 1357810la** [comment]
> 我遇到了同样的问题（Win 10）。为我修复它的方法是注释掉文件中的两行记录器代码。`/server/graph.py`
> 
> ```
> logger.info("freezing %d variables...", len(returned_variables))
> 
> logger.info("Converted %d variables to const ops.", how_many_converted) 
> ```

graph.py文件中没有这两行代码是什么情况啊

**Comment by 1357810la** [comment]
![8193307fec846524483f684d3f64dc9](https://user-images.githubusercontent.com/100670240/199234065-9743755f-73a0-4961-97f2-a2da4169480a.png)
有知道这个的吗
