### ISSUE TITLE
Docker without gpu/cuda

### ISSUE THREAD

**Issue by kramer425** [hanxiao/bert-as-service#209]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Is it possible to run this as a container on a machine without a gpu/cuda?

I've installed nvidia-docker2, but did not install cuda - no gpu on this debian 9 vm. I'm only trying to run it in cpu mode. 

My entrypoint.sh
```bash
#!/bin/sh
bert-serving-start -num_worker=1 -cpu -model_dir /model
```

and running the container via:
```bash
docker run --runtime nvidia \
-dit \
-p 5555:5555 \
-p 5556:5556 \
-v /root/Documents/uncased_L-12_H-768_A-12:/model \
-e CUDA_VISIBLE_DEVICES='0' \
-t bert-as-service
```

Then this issue shows up:
```bash
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 1 caused \\\"error running hook: exit status 1, stdout: , stderr: exec command: [/usr/bin/nvidia-container-cli --load-kmods configure --ldconfig=@/sbin/ldconfig --device=all --compute --utility --require=cuda>=9.0 --pid=11555 /var/lib/docker/overlay2/90c8bd366d6e8bac364db0b77bda718df54c00b8e75149d19edd9b248f34040a/merged]\\\\nnvidia-container-cli: initialization error: driver error: failed to process request\\\\n\\\"\"": unknown.
```

**Comment by kramer425** [comment]
I was able to solve this by changing the base image to one that doesn't need nvidia-docker:
```
FROM tensorflow/tensorflow:1.12.0-py3
```

Rebuilt, and using the same run command without the nvidia runtime works:
```
docker run -dit \
-p 5555:5555 \
-p 5556:5556 \
-v /root/Documents/uncased_L-12_H-768_A-12:/model \
-e CUDA_VISIBLE_DEVICES='0' \
-t bert-as-service
```

**Comment by haiker2011** [comment]
@kramer425 I follow your mathod ,But I got  `F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine.
Aborted (core dumped)`

**Comment by kramer425** [comment]
> 
> 
> @kramer425 I follow your mathod ,But I got `F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.2 instructions, but these aren't available on your machine. Aborted (core dumped)`

Are you able to install that version of tensorflow on your machine without docker? Maybe try to see if there are other base images that will support your cpu.
