### ISSUE TITLE
Can request don't use bert-as-service client

### ISSUE THREAD

**Issue by policeme** [hanxiao/bert-as-service#219]
I want to use you server structure into my project, I have a question , Can I request bert-as-service server don't use bert-as-service client, just use python request? because in your code, I see that you use zmq to request the bert-as-service server.

**Comment by hanxiao** [comment]
Besides TCP request, you may use HTTP request https://github.com/hanxiao/bert-as-service#using-bert-as-service-to-serve-http-requests-in-json

There is no such thing as "a python request", a request has to rely on some interface, e.g. TCP or HTTP.

**Comment by policeme** [comment]
ok, I will try, thank you for your reply.
