### ISSUE TITLE
problem of worker work?

### ISSUE THREAD

**Issue by policeme** [hanxiao/bert-as-service#223]
I have a question, if I start this service with 2 worker, I have one request,  No matter how many strings are in the request list, the service always use one worker?

**Comment by policeme** [comment]
@hanxiao

**Comment by hanxiao** [comment]
No. Depending on your batch size, `max_batch_size` and `prefetch_size ` on the server side. A request may be decomposed into multiple subtasks and computed on multiple devices. 

More details: https://bert-as-service.readthedocs.io/en/latest/source/server.html#server-side-api  
Or read the source of the ventilator: https://github.com/hanxiao/bert-as-service/blob/56e7099457c3eafc6f1f882898efab7e36669ed8/server/bert_serving/server/__init__.py#L173
