### ISSUE TITLE
How to obtain the word embeddings

### ISSUE THREAD

**Issue by lucyboll** [hanxiao/bert-as-service#23]
Thanks for this service, I can get the sentence embeddings. I want to know how can I get the context representations for every token in the sentence through the service. Thank you very much.

**Comment by hanxiao** [comment]
good point. in principle, there is nothing stops us from getting the word embedding. I also understand the importance of this feature as people may want to use this service in an ELMO-like fashion. It's just the API and interface might be changed a little bit when considering word embedding.

So point taken, I will consider it as a feature and implement it soon.

**Comment by hanxiao** [comment]
@lucyboll fyi, this is done in [v1.1](https://github.com/hanxiao/bert-as-service/tree/v1.1), please check out latest master and [this thread](https://github.com/hanxiao/bert-as-service#q-how-can-i-get-word-embedding-instead-of-sentence-embedding) for more details.

close #25
