### ISSUE TITLE
UserWarning: "show_tokens=True" even after setting False

### ISSUE THREAD

**Issue by yuchenlin** [hanxiao/bert-as-service#230]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ x] Are you running the latest `bert-as-service`?
* [ x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.10.0
- Python version: 3.6
- `bert-as-service` version: 1.8.1
- GPU model and memory:
- CPU model and memory: i7 

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -pooling_strategy REDUCE_MAX -max_seq_len 60 -model_dir ./uncased_L-12_H-768_A-12/ -num_worker=1 -port 22002
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
sent_vecs = bc.encode(sents, show_tokens=False)
```

Then this issue shows up:

UserWarning: "show_tokens=True", but the server does not support showing tokenization info to clients.
here is what you can do:
...

**Comment by ironflood** [comment]
Are you certain you updated to 1.8.1 the client and server on both sides? This issue is the same as the one I was facing in 1.8.0 which has then been solved.
