### ISSUE TITLE
 bert_embedding = BertEmbeddings('bert-base-multilingual-cased')   File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/flair/embeddings.py", line 874, in __init__     self.model = BertModel.from_pretrained(bert_model)   File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 473, in from_pretrained     resolved_archive_file = cached_path(archive_file, cache_dir=cache_dir)   File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/pytorch_pretrained_bert/file_utils.py", line 88, in cached_path     return get_from_cache(url_or_filename, cache_dir)   File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/pytorch_pretrained_bert/file_utils.py", line 178, in get_from_cache     .format(url, response.status_code)) OSError: HEAD request failed for url https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-multilingual-cased.tar.gz with status code 500

### ISSUE THREAD

**Issue by Harika-3196** [hanxiao/bert-as-service#234]
**code_snippet:**

def bert(sen):                # bert embeddings for given sentence
    sen=Sentence(sen)
    bert_embedding = BertEmbeddings('bert-base-multilingual-cased')
    document_embeddings_bert = DocumentPoolEmbeddings([bert_embedding])
    document_embeddings_bert.embed(sen)

    return sen.get_embedding()  

**OUTPUT:** 
bert("The grass is green") # calling a function
tensor([[ 0.3664, 0.4660, -0.0278, ..., 0.4712, 1.0407, 0.4369]]

It worked very well for my half dataset 
but after some time it stops throwing the following error as shown below 

**ERROR:**

bert_embedding = BertEmbeddings('bert-base-multilingual-cased')
  File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/flair/embeddings.py", line 874, in __init__
    self.model = BertModel.from_pretrained(bert_model)
  File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 473, in from_pretrained
    resolved_archive_file = cached_path(archive_file, cache_dir=cache_dir)
  File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/pytorch_pretrained_bert/file_utils.py", line 88, in cached_path
    return get_from_cache(url_or_filename, cache_dir)
  File "/home/ubuntu/anaconda3/envs/conda_python3/lib/python3.6/site-packages/pytorch_pretrained_bert/file_utils.py", line 178, in get_from_cache
    .format(url, response.status_code))

**Comment by hanxiao** [comment]
irrelevant
