### ISSUE TITLE
Support for FP16 (mixed precision) trained models

### ISSUE THREAD

**Issue by miweru** [hanxiao/bert-as-service#235]
I trained a little german BERT Model with FP16 and tensorflow, so the Nvidia suggestion https://github.com/google-research/bert/pull/255
the suggestions are hosted in this repository
https://github.com/thorjohnsen/bert/tree/gpu_optimizations

Training works fine, but bert-as-service doesn't work with that, because of the tensorflows typechecks when loading the graph. Same problem with the fp16 option activated.

Is there a simple way of modifiing bert-as-service or convert the model so i can use the embeddings with bert-as-service?

Thank you!

**Comment by hanxiao** [comment]
I wasn't aware of [this branch](https://github.com/thorjohnsen/bert/tree/gpu_optimizations) when implementing `fp16` support. In bert-as-service fp16 support is a basically preprocessing *in the inference stage* (or a postprocessing in the training stage if you like), meaning that all float32 variables are freezed to float16 in `graph.py` before serving. See:
https://github.com/hanxiao/bert-as-service/blob/179356874048338b2374447aa0ae42e3c3578b19/server/bert_serving/server/graph.py#L153
