### ISSUE TITLE
Conda install command? 

### ISSUE THREAD

**Issue by ShirleyHan6** [hanxiao/bert-as-service#246]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

I tried to install this package while building an image using a docker file then this error occurred. 

CondaValueError: too few arguments, must supply command line package specs or --file

The command '/bin/sh -c conda install -c bert-serving-server' returned a non-zero code: 1

Then I tried both "conda install bert-serving-server' and "conda install -c load bert-serving-server", then it says package not available in channel.

**Comment by hanxiao** [comment]
I personally don't use conda and not familiar with its eco-system. Maybe related: https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment
