### ISSUE TITLE
how to get word hidden states?

### ISSUE THREAD

**Issue by susht3** [hanxiao/bert-as-service#25]
like QA tasks, it uses the hidden states of each word in the passage, to predict the answer, but the service only returns the last hidden states of a sequence, could you support word vectors?

**Comment by hanxiao** [comment]
correct. that’s why i said only API of my side needs to be changed a little
bit.

Colanim <notifications@github.com>于2018年11月20日 周二上午9:27写道：

**Comment by hanxiao** [comment]
this issue is duplicated with #23 , which I will implement soon.
@susht3 also notice that the service does not return the last hidden states of a sequence, please refer to https://github.com/hanxiao/bert-as-service#q-what-are-the-available-pooling-strategies

**Comment by hanxiao** [comment]
@susht3 fyi, this is done in v1.1, please check out latest master and this thread for more details.
