### ISSUE TITLE
Is there any need to transform the original model(released by google) to a fp16 model when using fp16 mode to inference? 

### ISSUE THREAD

**Issue by xyfZzz** [hanxiao/bert-as-service#250]
Thank you for your sharing! 

Is there any need to transform the original model(released by google) to a fp16 model when using fp16 mode to inference?  If it is needed, do you know any methods to transform it? Thank you!

**Comment by hanxiao** [comment]
What do you mean "transform"?

You can use `fp16` out-of-the-box in `bert-as-service`. [No extra preprocessing needed.](https://github.com/hanxiao/bert-as-service#speed-wrt--fp16-and--xla)

**Comment by xyfZzz** [comment]
> What do you mean "transform"?
> 
> You can use `fp16` out-of-the-box in `bert-as-service`. [No extra preprocessing is needed.](https://github.com/hanxiao/bert-as-service#speed-wrt--fp16-and--xla)

Thank you, I found that float32 variables are freezed to float16 in `graph.py` when using `fp16` mode, can this `graph.py`  work when the network changed?

**Comment by hanxiao** [comment]
yes. see https://github.com/hanxiao/bert-as-service/issues/235#issuecomment-463451501
