### ISSUE TITLE
Internal Server Error using curl

### ISSUE THREAD

**Issue by pannous** [hanxiao/bert-as-service#251]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

- OS Platform and Distribution: Linux Ubuntu 18.04.1 LTS
- TensorFlow installed from (source or binary): binary 
- TensorFlow version:   tensorflow-gpu                1.12.0
- Python version:  Python 3.6.7
- `bert-as-service` version: bert-serving-server[http] in /usr/local/lib/python3.6/dist-packages (1.8.2)
- CPU model and memory:  AMD 16GB

---

### Description

I'm using this command to start the server:

```bash
bert-serving-start -model_dir bert/multi_cased_L-12_H-768_A-12 -num_worker=1 -cpu -http_port 8125
```

and calling the server via:
```
curl -X POST http://0.0.0.0:8125/encode   -H 'content-type: application/json'   -d '{"id": 123,"texts": ["hello world"], "is_tokenized": false}'
```

Then this issue shows up:

```<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
```

server side:
```
* Running on http://0.0.0.0:8125/ (Press CTRL+C to quit)
I:WORKER-0:[__i:gen:506]:ready and listening!
I:PROXY:[htt:enc: 47]:new request from 127.0.0.1
I:VENTILATOR:[__i:_ru:164]:new encode request	req id: 2	size: 1	client: b'6dc0a555-3239-474f-807e-66e3cbb17ccb'
I:SINK:[__i:_ru:317]:job register	size: 1	job id: b'6dc0a555-3239-474f-807e-66e3cbb17ccb#2'
I:WORKER-0:[__i:gen:514]:new job	socket: 0	size: 1	client: b'6dc0a555-3239-474f-807e-66e3cbb17ccb#2'
I:WORKER-0:[__i:_ru:490]:job done	size: (1, 768)	client: b'6dc0a555-3239-474f-807e-66e3cbb17ccb#2'
I:SINK:[__i:_ru:297]:collect b'EMBEDDINGS' b'6dc0a555-3239-474f-807e-66e3cbb17ccb#2' (E:1/T:0/A:1)
I:SINK:[__i:_ru:306]:send back	size: 1	job id: b'6dc0a555-3239-474f-807e-66e3cbb17ccb#2'
127.0.0.1 - - [26/Feb/2019 17:56:31] "POST /encode HTTP/1.1" 500 -
```

That's not very helpful, is it? Any way to increase logging?

**Comment by pannous** [comment]
Btw it works using python code.

**Comment by hanxiao** [comment]
can not reproduce
