### ISSUE TITLE
error in Visualisation of encoding

### ISSUE THREAD

**Issue by shivamakhauri04** [hanxiao/bert-as-service#253]
Getting an error :

_pickle.PicklingError: Can't pickle <class '__main__.args_namedtuple'>: attribute lookup args_namedtuple on __main__ failed

**Comment by thommiano** [comment]
It get this same error when I try to spin up the BERT server in python, copying example 7.
```
base = {
    'model_dir': '/data/models/bert/uncased_L-12_H-768_A-12/',
    'num_worker': 1,
    'max_seq_len': 283,
    'pooling_strategy': PoolingStrategy.REDUCE_MEAN,
    'num_repeat': 10,
    'port': 5555,
    'port_out': 5556,
    'client_batch_size': 4096,
    'max_batch_size': 256,
    'num_client': 1,
    'pooling_layer': [-2],
    'gpu_memory_fraction': 0.5,
    'xla': False,
    'cpu': False,
    'verbose': False,
    'device_map': []
}
args = namedtuple('args_namedtuple', ','.join(base.keys()))
for k, v in base.items():
    setattr(args, k, v)
server = BertServer(args)
server.start()
```
><class '__main__.args_namedtuple'>
I:VENTILATOR:[__i:__i: 66]:freeze, optimize and export graph, could take a while...
Traceback (most recent call last):
  File "./src/encode_with_bert.py", line 114, in <module>
    server = BertServer(args)
  File "/usr/local/lib/python3.5/dist-packages/bert_serving/server/__init__.py", line 70, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 253, in apply
    return self.apply_async(func, args, kwds).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class '__main__.args_namedtuple'>: attribute lookup args_namedtuple on __main__ failed

**Comment by hanxiao** [comment]
One should not use `namedtuple` as args to start a server. I know I wrote something like that in an old version, but this is depreciated. The visualization script is not updated accordingly I guess.

So first, update the package via `pip install -U bert-serving-client bert-serving-server`

To use BertServer in your code, please do the following:

```python

from bert_serving.server.helper import get_args_parser
args = get_args_parser().parse_args(['-model_dir', 'YOUR_MODEL_PATH_HERE',
                                             '-port', '5555',
                                             '-port_out', '5556',
                                             '-max_seq_len', 'NONE',
                                             '-mask_cls_sep',
                                             '-cpu'])
server = BertServer(args)
server.start()
```

Note that it's basically mirroring the arg-parsing behavior in CLI, so everything in that `.parse_args([])` list should be string, e.g. `['-port', '5555']` not `['-port', 5555]`.
