### ISSUE TITLE
How to cite Bert as a service?

### ISSUE THREAD

**Issue by drussellmrichie** [hanxiao/bert-as-service#257]
Thanks for providing a great package. I'd love to cite it in one or two things I'm preparing. Is there a BibTex citation I can use?

**Comment by hanxiao** [comment]
Thanks for being an awesome user!

Two ways of citing it:
1. `\footnote{https://github.com/hanxiao/bert-as-service}`
2. 
```latex
@misc{xiao2018bertservice,
  title={bert-as-service},
  author={Xiao, Han},
  howpublished={\url{https://github.com/hanxiao/bert-as-service}},
  year={2018}
}
```
