### ISSUE TITLE
dashboard can not work correctly

### ISSUE THREAD

**Issue by policeme** [hanxiao/bert-as-service#259]
@hanxiao I started the dashborad, but it seemed not work correctly, the x coordinate start is the web page start time, not last 60 minutes time, all the chart are same, Is it a bug?
![image](https://user-images.githubusercontent.com/30991932/53613015-a14f1000-3c0f-11e9-865e-04d6368022d8.png)

**Comment by hanxiao** [comment]
Not a bug. It's written in the frontend code. For performance sake and simplicity, sever does not persist history data.

Feel free to change the behavior by yourself. Note that dashboard (and its UX/UI) serves merely as an toy example, maintaining it is not part of my priority work.
