### ISSUE TITLE
bert-serving-start: command not found，有人遇见过吗

### ISSUE THREAD

**Issue by ares5221** [hanxiao/bert-as-service#261]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:
command not found
...

**Comment by hanxiao** [comment]
without any information about version and OS you are using, there's little that I can help with.

please refer to https://github.com/hanxiao/bert-as-service/issues/194

**Comment by greggeilfuss** [comment]
I am having the same problem. Using the directions found on https://bert-as-service.readthedocs.io/en/latest/tutorial/http-server.html I got 'command not found.'  I'm running...
Ubuntu 18.04 LTS, 
Python 3.6.7, 
Flask==1.0.2, 
Flask-Compress==1.4.0,
Flask-Cors==3.0.7, 
Flask-JSON==0.3.3, 
bert-serving-client==1.8.9
bert-serving-server==1.8.9. 

1. The version of bert-serving-*  is a concern because GitHub releases shows 1.8.1 as the most recent version.
2. when executing bert-serving-start I receive "bert-serving-start: command not found"

**Comment by cuiguohua** [comment]
> Please re-open this issue:
> I am having the same problem. Using the directions found on https://bert-as-service.readthedocs.io/en/latest/tutorial/http-server.html I got 'command not found.' I'm running...
> Ubuntu 18.04 LTS,
> Python 3.6.7,
> Flask==1.0.2,
> Flask-Compress==1.4.0,
> Flask-Cors==3.0.7,
> Flask-JSON==0.3.3,
> tensorboard==1.13.1
> tensoflow==1.13.1
> tensorflow-estimator==1.13.0
> bert-serving-client==1.8.9
> bert-serving-server==1.8.9
> 
> 1. The version of bert-serving-*  is a concern because GitHub releases shows 1.8.1 as the most recent version.
> 2. when executing bert-serving-start I receive "bert-serving-start: command not found"
> 
> Note: I did see the other issue: #194, and suspect it's the same, however it seems as though it's closed as well, and is on the Windows OS. Therefore I'm commenting here.

try to use sudo pip/pip3 ...

**Comment by ares5221** [comment]
> Please re-open this issue:
> I am having the same problem. Using the directions found on https://bert-as-service.readthedocs.io/en/latest/tutorial/http-server.html I got 'command not found.' I'm running...
> Ubuntu 18.04 LTS,
> Python 3.6.7,
> Flask==1.0.2,
> Flask-Compress==1.4.0,
> Flask-Cors==3.0.7,
> Flask-JSON==0.3.3,
> tensorboard==1.13.1
> tensoflow==1.13.1
> tensorflow-estimator==1.13.0
> bert-serving-client==1.8.9
> bert-serving-server==1.8.9
> 
> 1. The version of bert-serving-*  is a concern because GitHub releases shows 1.8.1 as the most recent version.
> 2. when executing bert-serving-start I receive "bert-serving-start: command not found"
> 
> Note: I did see the other issue: #194, and suspect it's the same, however it seems as though it's closed as well, and is on the Windows OS. Therefore I'm commenting here.

you may find bert-serving-start in .local/bin this folder,and run it with python
