### ISSUE TITLE
How to fix the word embeddings in bert?

### ISSUE THREAD

**Issue by weizhenzhao** [hanxiao/bert-as-service#267]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ ] Are you running the latest `bert-as-service`? pip install bert-client , pip install bert-server
* [ ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?yes
* [ ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version:1.13.0
- Python version:3.5.6
- `bert-as-service` version: 
- GPU model and memory:cpu
- CPU model and memory:i5 7代

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:

Hi Dear

my question is when I'm using the bert-as-service as the back-end for the rasa_nlu part
I found that every time a same sentence sent to the bert server return different embeddings

for example
the first time  "如何查询社保"  -----> bert server ---->[0.213,0.234,0.672,..........]
a second time  "如何查询社保"  -----> bert server ---->[0.283,0.294,0.802,..........]

why the same sentence has different embedding? because I find that in the later text classification process it's hard for me to train if the embedding is different for the same sentence every time
[0.213,0.234,0.672,..........]
[0.283,0.294,0.802,..........]

can you teach me how to fix the embedding for the same sentence?

Thanks
weizhen

...

**Comment by hanxiao** [comment]
sorry, can't reproduce.

```python
import numpy.testing
numpy.testing.assert_almost_equal(bc.encode(['如何查询社保']), bc.encode(['如何查询社保']))
```

**Comment by ipponjasper** [comment]
Hi,

I have the same issue, but only when trying to embed with a fine tuned model.
I am starting up the BERT server with:
`bert-serving-start -model_dir=C:/.../multi_cased_L-12_H-768_A-12/ -tuned_model_dir=C:/...` 
`-ckpt_name=model.ckpt-6258 -num_worker=1 -max_seq_len=128 -cased_tokenization`

I am starting up the client with:
`from bert_serving.client import BertClient`
`bc = BertClient()`

When I now use:
`encoding=bc.encode(['Why does this not work?'])` 
This gives: array([[ 5.51824450e-01,  5.25670648e-01,  6.89625621e-01....]

However, when I close the server and start a new one in exactly the same manner and I use:
`encoding_2=bc.encode(['Why does this not work?'])`
This gives: array([[-2.78031558e-01, -3.44201356e-01, -1.15424120e+00,...]

This does not happen when using the standard BERT model without fine-tuning. 
I am looking forward to hearing from you if I am doing something wrong.

**Comment by lexi-dyfrgi** [comment]
Hi, 
I have the same issue with the fine-tuned BERT. Please answer!
