### ISSUE TITLE
AttributeError: 'Response' object has no attribute 'content' when asynchronous encoding

### ISSUE THREAD

**Issue by wingsyuan** [hanxiao/bert-as-service#269]
Hi，
when I follow the instruction Asynchronous encoding, there was an error:

python example2.py 5555 5556

sending all data without blocking...
all sent!
now waiting until all results are available...
Traceback (most recent call last):
  File "example2.py", line 39, in <module>
    vecs = bc.fetch_all(concat=True)
  File "/home/anaconda3/lib/python3.6/site-packages/bert_serving/client/__init__.py", line 336, in fetch_all
    tmp = [v.content for v in tmp]
  File "/home/anaconda3/lib/python3.6/site-packages/bert_serving/client/__init__.py", line 336, in <listcomp>
    tmp = [v.content for v in tmp]
AttributeError: 'Response' object has no attribute 'content'

Is there any solution? thanks very much!

**Comment by wingsyuan** [comment]
Change v.content  to v.embedding , problem is solved

**Comment by hanxiao** [comment]
fyi, this issue is fixed in #271 and the new feature is available since 1.8.4, please do
```bash
pip install -U bert-serving-server bert-serving-client
```
for the update.
