### ISSUE TITLE
how to run monitor 

### ISSUE THREAD

**Issue by mullerhai** [hanxiao/bert-as-service#273]
when I want to run  the  monitor  with failed

bert-serving-start  -http_port 8001  -model_dir=/Users/hainingzhang/Downloads/chinese_L-12_H-768_A-12 -tuned_model_dir=/Documents/bert_output/ -ckpt_name=model.ckpt-18  -num_worker=4 -pooling_strategy=CLS_TOKEN  

:VENTILATOR:[__i:_ru:148]:new config request	req id: 1	client: b'91810d36-4eea-40ad-9fb3-3ad8ead1f8f0'
I:SINK:[__i:_ru:320]:send config	client b'91810d36-4eea-40ad-9fb3-3ad8ead1f8f0'
I:VENTILATOR:[__i:_ru:148]:new config request	req id: 1	client: b'2b3019dd-3792-4ec2-bc7f-d5d900252ab7'
I:SINK:[__i:_ru:320]:send config	client b'2b3019dd-3792-4ec2-bc7f-d5d900252ab7'
 * Serving Flask app "bert_serving.server.http" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8001/ (Press CTRL+C to quit)
 * Running on http://0.0.0.0:8001/ (Press CTRL+C to quit)
127.0.0.1 - - [14/Mar/2019 16:43:03] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2019 16:43:03] "GET /robots.txt?1552552983893 HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2019 16:43:05] "GET /favicon.ico HTTP/1.1" 404 -
I:WORKER-1:[__i:gen:506]:ready and listening!
I:WORKER-0:[__i:gen:506]:ready and listening!
I:WORKER-2:[__i:gen:506]:ready and listening!
I:WORKER-3:[__i:gen:506]:ready and listening!

### run service   start is successful

but when I  open  the webpae link  is fail in  chrome  or Safari
http://0.0.0.0:8001/index.html
http://0.0.0.0:8001

I dont know why

127.0.0.1 - - [14/Mar/2019 16:43:49] "GET /robots.txt?1552553029264 HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2019 16:44:00] "GET /robots.txt?1552553040140 HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2019 16:44:31] "GET /plugin/dashboard/index.html HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2019 16:44:31] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2019 16:49:33] "GET /index.html HTTP/1.1" 404 -
127.0.0.1 - - [14/Mar/2019 16:49:33] "GET /favicon.ico HTTP/1.1" 404 -

**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ ] Are you running the latest `bert-as-service`?
* [ ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:

...

**Comment by mullerhai** [comment]
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by hanxiao** [comment]
dashboard should run separately. just [download everything here](https://github.com/hanxiao/bert-as-service/tree/master/plugin/dashboard) and open index.html, fill in the ip and port.

**Comment by arianpasquali** [comment]
This is old but might be helpful to someone. 

@mullerhai make sure you edit your bert-server address at bindings.js 

The ip address and the context must point to your bert http service 
https://github.com/hanxiao/bert-as-service/blob/0fb1814d6368ff824e90b386a3bf65cab514a067/plugin/dashboard/bindings.js#L6
