### ISSUE TITLE
why the same sentence show different embedding?

### ISSUE THREAD

**Issue by wingsyuan** [hanxiao/bert-as-service#275]
Hi,

I try to embed 200000 sentence, and I use two way to embed as follow:
 
one is that "data" contain all the list of string:

    with open('a1') as fp:
        data = [v.strip('\n') for v in fp]
    vectors = bc.encode(data)

the other is that "line" contain one list of string:

    line = f3.readline()
    line = line.strip('\n')   
    while line:
        vectors = bc.encode([line])       
        line = f3.readline()

but results show that the embedding of the same sentence are different in different way mentioned above.

anyone  tell me why?
   

Here is my code:

     import sys
     import time
     from bert_serving.client import BertClient

     if __name__ == '__main__':
         bc = BertClient(port=int(sys.argv[1]), port_out=int(sys.argv[2]), show_server_config=True, output_fmt='list')   

    with open('a1') as fp:
        data = [v.strip('\n') for v in fp]
    vectors = bc.encode(data) 

    f3 = open("a1")
    f4 = open("output2.txt", 'a+')
    line = f3.readline()
    line = line.strip('\n')
    print([line])
    while line:
        vectors = bc.encode([line])
        f4.write(str(vectors))
        line = f3.readline()
    f3.close()
    f4.close()

**Comment by hanxiao** [comment]
impossible. the embedding is deterministic. must be some inconsistency on your input.

1. you should not use `=` to assert if two vectors are equal or not, see https://github.com/hanxiao/bert-as-service/issues/167#issuecomment-450928500

2. the best way to debug is to enable `-show_tokens_to_client` on the server and check the tokenization returned. see https://github.com/hanxiao/bert-as-service/#using-your-own-tokenizer

**Comment by hanxiao** [comment]
a minimum example can be found here
https://github.com/hanxiao/bert-as-service/issues/267#issuecomment-473158634

```python
import numpy.testing
from bert_serving.client import BertClient

with BertClient() as bc:
    numpy.testing.assert_almost_equal(bc.encode(['如何查询社保']), bc.encode(['如何查询社保']))

# no exception is raised
```

**Comment by wingsyuan** [comment]
@hanxiao 

     import sys
     import time

     from bert_serving.client import BertClient

     if __name__ == '__main__':
     bc = BertClient(port=int(sys.argv[1]), port_out=int(sys.argv[2]), show_server_config=True, output_fmt='list')
    

     with open('a1') as fp:
        data = [v.strip('\n') for v in fp]   

    vectors = bc.encode(data)
    f2 = open("output1.txt", 'a+')
    f2.write(str(vectors))
    f2.close()

    f3 = open("a1")
    f4 = open("output2.txt", 'a+')
    line = f3.readline()
    #print(line)
    line = line.strip('\n')
    print([line])
    while line:
        vectors = bc.encode([line])
        f4.write(str(vectors))
        line = f3.readline()
    f3.close()
    f4.close()

**Comment by wingsyuan** [comment]
@hanxiao 
 When I use numpy.testing.assert_almost_equal, result is as follow:
the two way of reading the file make them different...bu I don't know why

(shapes (1, 2, 1024), (2, 1, 1024) mismatch)
 x: array([[[-0.2231579,  0.3980872,  0.5846128, ...,  0.2056947,
         -0.1711089, -0.2720026],
        [-0.1779817,  0.5355911,  0.62152  , ...,  0.0466648,
         -0.0653483, -0.1269193]]])
 y: array([[[-0.2231579,  0.3980872,  0.5846128, ...,  0.2056947,
         -0.1711089, -0.2720026]],

**Comment by hanxiao** [comment]
you pointed out yourself `(shapes (1, 2, 1024), (2, 1, 1024) mismatch)`

**Comment by wingsyuan** [comment]
hmm...
Thanks for your help, makebe a little mistake，

but when I use the following code(100 sentence in the same file, two ways of reading it mentioned above), there are still different between them:

#shape(1,100,1024) and shape(100,1,1024),all should be the first sentence
numpy.testing.assert_almost_equal(vectors3[0][0], vectors_n[0][0])

but the result is as follow ,they are very similar but not the same:
(mismatch 77.34375%)
 x: array([-0.1779817,  0.5355914,  0.6215196, ...,  0.0466645, -0.0653478,
       -0.1269192])
 y: array([-0.1779817,  0.5355911,  0.62152  , ...,  0.0466648, -0.0653483,
       -0.1269193])

[CLS]', 'action', 'taken', 'on', 'parliament', "'", 's', 'resolutions', ':', 'see', 'minutes', '[SEP]']]
['[CLS]', 'action', 'taken', 'on', 'parliament', "'", 's', 'resolutions', ':', 'see', 'minutes', '[SEP]']


and if I handle a big text, can I choose the following way to get the embedding of each sentence?
f3 = open("a1")
f4 = open("output2.txt", 'a+')
line = f3.readline()
#print(line)
line = line.strip('\n')
print([line])
while line:
    vectors = bc.encode([line])
    f4.write(str(vectors))
    line = f3.readline()
f3.close()
f4.close()
