### ISSUE TITLE
how to stop bert-serving

### ISSUE THREAD

**Issue by HorningFeng** [hanxiao/bert-as-service#282]
I can use `bert-serving-start` to start a serving, but how can I stop the serving.
I don't see something like `bert-serving-stop`. Does `kill PID` will do harm?

**Comment by hanxiao** [comment]
duplicate to #208

**Comment by hanxiao** [comment]
fyi, this issue has been fixed in #286 and the new feature is available since 1.8.6. Please do
```bash
pip install -U bert-serving-server bert-serving-client
```
for the update.

To shutdown a server, please do `bert-serving-terminate --help` and [check README](https://github.com/hanxiao/bert-as-service#starting-bertserver-from-python) for details.

**Comment by tvrbanec** [comment]
Can bert-serving-server work in background?
