### ISSUE TITLE
why large max_seq_len cause blocking

### ISSUE THREAD

**Issue by wenbotse** [hanxiao/bert-as-service#283]
I try different max_seq_len , I found the largest size is about 512, if i set max_seq_len=1024，when calling bc.encode() it will be blocked ,Is that true or i tried the wrong way.

bert-serving-start -num_worker=$1 -model_dir /model -max_seq_len=512

**Comment by hanxiao** [comment]
if you read closely to the log, you will see the upper bound of `max_seq_len` in Google's pretrained BERT is 512. Thus, it makes no sense to use >512

Besides, I would suggest to use `-max_seq_len=NONE`, which can nearly always speedup the inference.

**Comment by michaelcapizzi** [comment]
I understand @wenbotse 's confusion though.  When I read this...

```
maximum length of sequence, longer sequence will be trimmed on the right side. Set it to NONE for dynamically using the longest sequence in a (mini)batch.
```

...it means to me that there is *no* max sequence length, and I *can* submit a sequence larger than 512 and it will still be processed, not truncated.

Although your statement above @hanxiao is true that the `BERT` model was trained on sequences no longer than 512, the original paper that introduced this architecture, "Attention is All You Need" (https://arxiv.org/pdf/1706.03762.pdf), claimed that infinite lengths *can* be processed even though the model was only trained on sequences of length 512.

```
We chose the sinusoidal version because it may allow the model to extrapolate to sequence lengths longer than the ones encountered during training.
```

In this case, for this project, the description of the `max_seq_len` argument is therefore unclear to me.

I *think* what it is saying is "by setting to NONE, we will batch your documents to the longest length *as long as* it is still shorter than 512 tokens."

It would be more clear if there was still a comment indicating that if set to `NONE`, sequences longer than 512 will *still* be truncated.

**Comment by michaelcapizzi** [comment]
@wenbotse the original `BERT` repository has an issue about this, and someone provides the suggestion for handling sequences > 512 with "windowing": https://github.com/google-research/bert/issues/66
