### ISSUE TITLE
Get NaN when I run in GPU, but run successfully in CPU

### ISSUE THREAD

**Issue by zjwzcn07** [hanxiao/bert-as-service#289]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Red Hat 4.8.3-9
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.12
- Python version: 3.5
- `bert-as-service` version: v1.8.6
- GPU model and memory: Tesla P100 16G * 4
- CPU model and memory: 64G

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

CPU
```bash

bert-serving-start -model_dir=../../chinese_L-12_H-768_A-12 -tuned_model_dir=../../textSimilar/ -ckpt_name=model.ckpt-701 -max_seq_len=256 -max_batch_size=8 -cpu=True
```

GPU
```bash

bert-serving-start -model_dir=../../chinese_L-12_H-768_A-12 -tuned_model_dir=../../textSimilar/ -ckpt_name=model.ckpt-701 -max_seq_len=256 -max_batch_size=8 
```
and calling the server via:
```python
bc = BertClient(check_length=False)
bc.encode()
```

已经训练好了文本匹配的fine-tunning的模型，并且添加了自定义的pooling_strategy（最后一层过了个已经训练好的weight 和 bias网络）
然而预测时，用CPU跑的时候是正常的，能预测出正确的text_a ||| text_b 匹配结果，但是用GPU跑的时候对句子的encode就得到了一堆nan。我试图减小max_seq_length也没有用

server的运行日志

> I:GRAPHOPT:[gra:opt: 60]:build graph...
I:GRAPHOPT:[gra:opt:142]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:146]:optimize...
I:GRAPHOPT:[gra:opt:154]:freeze...
I:GRAPHOPT:[gra:opt:159]:write graph to a tmp file: /tmp/tmpimo7pfnh
I:VENTILATOR:[__i:__i: 74]:optimized graph is stored at: /tmp/tmpimo7pfnh
I:VENTILATOR:[__i:_ru:106]:bind all sockets
I:VENTILATOR:[__i:_ru:110]:open 8 ventilator-worker sockets
I:VENTILATOR:[__i:_ru:113]:start the sink
I:SINK:[__i:_ru:270]:ready
I:VENTILATOR:[__i:_ge:188]:get devices
I:VENTILATOR:[__i:_ge:221]:device map: 
                worker  0 -> gpu  0
                worker  1 -> gpu  1
                worker  2 -> gpu  2
                worker  3 -> gpu  3
I:WORKER-0:[__i:_ru:478]:use device gpu: 0, load graph from /tmp/tmpimo7pfnh
I:WORKER-1:[__i:_ru:478]:use device gpu: 1, load graph from /tmp/tmpimo7pfnh
I:WORKER-2:[__i:_ru:478]:use device gpu: 2, load graph from /tmp/tmpimo7pfnh
I:WORKER-3:[__i:_ru:478]:use device gpu: 3, load graph from /tmp/tmpimo7pfnh
I:WORKER-0:[__i:gen:506]:ready and listening!
I:WORKER-1:[__i:gen:506]:ready and listening!
I:WORKER-3:[__i:gen:506]:ready and listening!
I:WORKER-2:[__i:gen:506]:ready and listening!
I:VENTILATOR:[__i:_ru:148]:new config request   req id: 1       client: b'27e75165-0bac-4c93-8cc0-6e2f683badba'
I:SINK:[__i:_ru:320]:send config        client b'27e75165-0bac-4c93-8cc0-6e2f683badba'
I:VENTILATOR:[__i:_ru:164]:new encode request   req id: 2       size: 1405      client: b'27e75165-0bac-4c93-8cc0-6e2f683badba'
I:SINK:[__i:_ru:317]:job register       size: 1405      job id: b'27e75165-0bac-4c93-8cc0-6e2f683badba#2'
I:WORKER-0:[__i:gen:514]:new job        socket: 0       size: 4 client: b'27e75165-0bac-4c93-8cc0-6e2f683badba#2@0'
I:WORKER-2:[__i:gen:514]:new job        socket: 0       size: 4 client: b'27e75165-0bac-4c93-8cc0-6e2f683badba#2@8'

...

**Comment by DavenH** [comment]
I ran into something similar with #279. It was a mis-match of tensorflow version and cuda sdk version.

**Comment by zjwzcn07** [comment]
I deal it by using following command:
`sudo nvidia-smi -pm 1`

[reference this issue #254](https://github.com/hanxiao/bert-as-service/issues/254#issuecomment-473482746)

**Comment by zjwzcn07** [comment]
deal it

**Comment by ArturPrzybysz** [comment]
@zjwzcn07 You're the best, thank you for saving me with this issue...
