### ISSUE TITLE
bc = BertClient() hanging there forever

### ISSUE THREAD

**Issue by Masum06** [hanxiao/bert-as-service#292]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.13.1
- Python version: Python 3.6.7 :: Anaconda custom (64-bit)
- `bert-as-service` version: Latest right now
- GPU model and memory: RTX 2070
- CPU model and memory: Intel Core I7 8700

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server: 

```bash
bert-serving-start -model_dir cased_L-24_H-1024_A-16/ -num_worker=4 
```

and calling the server via:
```python
bc = BertClient()
```

Then this issue shows up: I started a server using the command mentioned above in one cmd terminal. Then from another terminal tried to create a BertClient() object using this command:
`bc = BertClient()`
But it is taking forever and not doing anything. I left it overnight, but nothing changed.

![image](https://user-images.githubusercontent.com/14367438/55040814-5b416c80-5054-11e9-910f-d62da5578d91.png)

Also tried 
```
bc = BertClient(ip='localhost')
```
Still nothing.

**Comment by hanxiao** [comment]
could you show the server log?

**Comment by Masum06** [comment]
```
(py36) E:\BERT>bert-serving-start -model_dir cased_L-24_H-1024_A-16/ -num_worker=4
usage: C:\Users\USER\AppData\Local\conda\conda\envs\py36\Scripts\bert-serving-start -model_dir cased_L-24_H-1024_A-16/ -num_worker=4
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = cased_L-24_H-1024_A-16/
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:[35mVENTILATOR[0m:freeze, optimize and export graph, could take a while...
I:[36mGRAPHOPT[0m:model config: cased_L-24_H-1024_A-16/bert_config.json
I:[36mGRAPHOPT[0m:checkpoint: cased_L-24_H-1024_A-16/bert_model.ckpt
I:[36mGRAPHOPT[0m:build graph...

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

I:[36mGRAPHOPT[0m:load parameters from checkpoint...
I:[36mGRAPHOPT[0m:optimize...
I:[36mGRAPHOPT[0m:freeze...
I:[36mGRAPHOPT[0m:write graph to a tmp file: C:\Users\USER\AppData\Local\Temp\tmp6r314uky
I:[35mVENTILATOR[0m:optimized graph is stored at: C:\Users\USER\AppData\Local\Temp\tmp6r314uky
I:[35mVENTILATOR[0m:bind all sockets
I:[35mVENTILATOR[0m:open 8 ventilator-worker sockets
I:[35mVENTILATOR[0m:start the sink
I:[32mSINK[0m:ready
I:[35mVENTILATOR[0m:get devices
W:[35mVENTILATOR[0m:only 1 out of 1 GPU(s) is available/free, but "-num_worker=4"
W:[35mVENTILATOR[0m:multiple workers will be allocated to one GPU, may not scale well and may raise out-of-memory
I:[35mVENTILATOR[0m:device map:
                worker  0 -> gpu  0
                worker  1 -> gpu  0
                worker  2 -> gpu  0
                worker  3 -> gpu  0
I:[33mWORKER-3[0m:use device gpu: 0, load graph from C:\Users\USER\AppData\Local\Temp\tmp6r314uky
I:[33mWORKER-2[0m:use device gpu: 0, load graph from C:\Users\USER\AppData\Local\Temp\tmp6r314uky
I:[33mWORKER-1[0m:use device gpu: 0, load graph from C:\Users\USER\AppData\Local\Temp\tmp6r314uky
I:[33mWORKER-0[0m:use device gpu: 0, load graph from C:\Users\USER\AppData\Local\Temp\tmp6r314uky
I:[35mVENTILATOR[0m:new config request        req id: 1       client: b'3045f5d8-d0c9-4bac-8058-e2c3cd4e4b9c'
I:[32mSINK[0m:send config     client b'3045f5d8-d0c9-4bac-8058-e2c3cd4e4b9c'
I:[35mVENTILATOR[0m:new encode request        req id: 2       size: 3 client: b'3045f5d8-d0c9-4bac-8058-e2c3cd4e4b9c'
I:[32mSINK[0m:job register    size: 3 job id: b'3045f5d8-d0c9-4bac-8058-e2c3cd4e4b9c#2'
```

**Comment by hanxiao** [comment]
worker is not started according to the log. reasons can be tf, nvidia-driver, cuda, etc., please search issue for the solution.
You should see "ready and listening" as illustrated in the animation here 
https://github.com/hanxiao/bert-as-service/#3-use-client-to-get-sentence-encodes

**Comment by Masum06** [comment]
Any clue from the server log what is failing specifically?

**Comment by Masum06** [comment]
I clicked a <space> on the cmd, and it showed 'ready and listening'. Now it's working. Thanks a lot! :)

**Comment by jannat5134** [comment]
hlw, I run bertclient() at google colab !!! but it also takes infinite time.

**Comment by atul611** [comment]
hlw, I run bertclient() at google colab !!! but it also takes infinite time. can i have the answer please!

**Comment by Masum06** [comment]
Hi, it is a pretty old library and I stopped using it. You should look into HuggingFace BERT, which should cover most use cases.

**Comment by nasrsuresh** [comment]
Similar issue (Running for more than half an hour) in google colab. Can anybody help resolve the same?
