### ISSUE TITLE
Cannot start Bert service

### ISSUE THREAD

**Issue by fadisius** [hanxiao/bert-as-service#297]
Hello, I have been struggling with trying to start Bert server service. 

`usage: C:\ProgramData\Anaconda3\envs\Bert\Scripts\bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12/ -num_worker=4
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /tmp/english_L-12_H-768_A-12/
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:[35mVENTILATOR[0m:freeze, optimize and export graph, could take a while...
I:[36mGRAPHOPT[0m:model config: /tmp/english_L-12_H-768_A-12/bert_config.json
I:[36mGRAPHOPT[0m:checkpoint: /tmp/english_L-12_H-768_A-12/bert_model.ckpt
E:[36mGRAPHOPT[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\bert\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\bert\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\Bert\Scripts\bert-serving-start.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\bert\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "c:\programdata\anaconda3\envs\bert\lib\site-packages\bert_serving\server\__init__.py", line 70, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable

No idea what it could be, not much info out there on this. I am currently running win 10, but also had issues with ubuntu. Any suggestions appreciated. 
Thanks 
`

**Comment by hanxiao** [comment]
this doesn't looks like the latest version of bert-as-service. please do 

```bash
pip install -U bert-serving-server bert-serving-client
```
for the update

**Comment by fadisius** [comment]
> this doesn't looks like the latest version of bert-as-service. please do
> 
> ```shell
> pip install -U bert-serving-server bert-serving-client
> ```
> 
> for the update

**Comment by fadisius** [comment]
> ```shell
> pip install -U bert-serving-server bert-serving-client
> ```

(Bert) C:\Users\fad>pip install -U bert-serving-server bert-serving-client
Requirement already up-to-date: bert-serving-server in c:\programdata\anaconda3\envs\bert\lib\site-packages (1.8.7)
Requirement already up-to-date: bert-serving-client in c:\programdata\anaconda3\envs\bert\lib\site-packages (1.8.7)
Requirement already satisfied, skipping upgrade: termcolor>=1.1 in c:\programdata\anaconda3\envs\bert\lib\site-packages (from bert-serving-server) (1.1.0)
Requirement already satisfied, skipping upgrade: numpy in c:\programdata\anaconda3\envs\bert\lib\site-packages (from bert-serving-server) (1.16.2)
Requirement already satisfied, skipping upgrade: six in c:\programdata\anaconda3\envs\bert\lib\site-packages (from bert-serving-server) (1.12.0)
Requirement already satisfied, skipping upgrade: pyzmq>=17.1.0 in c:\programdata\anaconda3\envs\bert\lib\site-packages (from bert-serving-server) (18.0.0)
Requirement already satisfied, skipping upgrade: GPUtil>=1.3.0 in c:\programdata\anaconda3\envs\bert\lib\site-packages (from bert-serving-server) (1.4.0)

**Comment by TianrenWang** [comment]
I am having the exact same issue. I followed your suggestion to get the latest version but it still didn't work.

**Comment by HamidAi** [comment]
I have the same issue
