### ISSUE TITLE
Cannot start Bert service.

### ISSUE THREAD

**Issue by fadisius** [hanxiao/bert-as-service#298]
Hi, sorry for reopening this issue but: 

I used pip install -U bert-serving-server bert-serving-client 
, I ran it again to be sure .

(Bert) C:\Users\fad>pip install -U bert-serving-server bert-serving-client
Requirement already up-to-date: bert-serving-server in c:\programdata\anaconda3\envs\bert\lib\site-packages (1.8.7)
Requirement already up-to-date: bert-serving-client in c:\programdata\anaconda3\envs\bert\lib\site-packages (1.8.7)

But i am still getting the Typeerror when I try to start Bert server:
usage: C:\ProgramData\Anaconda3\envs\Bert\Scripts\bert-serving-start -model_dir /tmp/english_L-12_H-768_A-12/ -num_worker=4
                 ARG   VALUE
__________________________________________________
           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = False
          device_map = []
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /tmp/english_L-12_H-768_A-12/
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:[35mVENTILATOR[0m:freeze, optimize and export graph, could take a while...
I:[36mGRAPHOPT[0m:model config: /tmp/english_L-12_H-768_A-12/bert_config.json
I:[36mGRAPHOPT[0m:checkpoint: /tmp/english_L-12_H-768_A-12/bert_model.ckpt
E:[36mGRAPHOPT[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\bert\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\bert\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\Bert\Scripts\bert-serving-start.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\bert\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "c:\programdata\anaconda3\envs\bert\lib\site-packages\bert_serving\server\__init__.py", line 70, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: 'NoneType' object is not iterable

**Comment by TianrenWang** [comment]
How did you solve this problem? I am having the same issue?
