### ISSUE TITLE
Support for multi-language version BERT

### ISSUE THREAD

**Issue by simonefrancia** [hanxiao/bert-as-service#3]
Hi, 
nice idea and nice repo! 
My question is if this server application is able to receive as input also a multi-language model of Bert, instead of English model.

I tried this command, but an error occurred.

```
>>> python app.py -num_worker=4 -model_dir ../multilingual_L-12_H-768_A-12/

parameters: 
batch_size_per_worker = 256
         max_seq_len = 25
           model_dir = ../multilingual_L-12_H-768_A-12/
          num_worker = 4
                port = 5555
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    server = BertServer(args)
  File "/src/text/BERT/bert-as-service/service/server.py", line 27, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
```

Thanks

**Comment by hanxiao** [comment]
1. It supports multi-lingual BERT off-the-shelf, I gave an English example in `README.md` but I'm using Chinese BERT pretrained by Google without any problem. No modification is needed.

2. Looks like you are using python 2, where `super()` is defined differently vs. py3. Please make sure you are using python > 3.5 and tensorflow >1.10 and fulfill `requirements.txt`

**Comment by CWJ666** [comment]
> 

i didn't find it in README.md，could you supply a latest example in another language?
