### ISSUE TITLE
docker build not ready and not listenning

### ISSUE THREAD

**Issue by weizhenzhao** [hanxiao/bert-as-service#307]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [ x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information** docker centos 7

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:1.13.0 cpu
- Python version:3.5.6
- `bert-as-service` version: 1.18
- GPU model and memory:no cuda driver installed
- CPU model and memory: i5 8GB memory

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:
in the Dockerfile:

`
/usr/local/python-3.5.6/bin/bert-serving-start -model_dir /usr/local/src/chinese_L-12_H-768_A-12 -cpu -http_port 3011 -tuned_model_dir=/usr/local/src/rasa_model_output -ckpt_name=model.ckpt-134
`

Then this issue shows up:
![image](https://user-images.githubusercontent.com/13706689/55489375-643dc980-5664-11e9-86e5-ab0878fa8f19.png)
it didn't show already and listening , and didn't show any error message.
is that my computer to slowly?

Thanks
Weizhen
...

**Comment by hanxiao** [comment]
version too old? please do `pip install -U` first

**Comment by weizhenzhao** [comment]
> version too old? please do `pip install -U` first

`
# base image
FROM centos

# MAINTAINER
MAINTAINER weizhen_zhao@163.com

# put rasa_model_output.zip into /usr/local/src and unpack rasa_model_output
ADD rasa_model_output.zip /usr/local/src/

# put chinese_L-12_H-768_A-12.zip into /usr/local/src and unpack chinese_L-12_H-768_A-12
ADD chinese_L-12_H-768_A-12.zip /usr/local/src/


# put Python-3.5.6.tgz into /usr/local/src and unpack Python-3.5.6.tgz
COPY Python-3.5.6.tgz /usr/local/src/


ENV SRC /usr/local/src/
WORKDIR ${SRC} 



# unpack python
RUN tar -xzvf ./Python-3.5.6.tgz
RUN yum -y install zlib zlib-devel gcc ncurses ncurses-devel


# install python
ENV PYTHONDIR /usr/local/src/Python-3.5.6
WORKDIR ${PYTHONDIR}
RUN ./configure --prefix=/usr/local/python-3.5.6
RUN yum -y install make openssl-devel bzip2-devel expat-devel gdbm-devel readline-devel sqlite-devel
RUN echo `pwd`
RUN make && make install

# set soft link for python3 and pip3
ENV root /
WORKDIR ${root} 
RUN ln -s /usr/local/python-3.5.6/bin/python3 /usr/bin/python3
RUN ln -s /usr/local/python-3.5.6/bin/pip3 /usr/bin/pip3

RUN pip3 install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple
RUN pip3 install -U bert-serving-server -i https://mirrors.aliyun.com/pypi/simple
RUN yum -y install unzip


WORKDIR ${SRC}

# unzip and start bert
RUN unzip rasa_model_output.zip
RUN unzip chinese_L-12_H-768_A-12.zip


# starting bert server
WORKDIR ${root}
RUN pip3 install tensorflow -i https://mirrors.aliyun.com/pypi/simple
COPY ./entrypoint.sh /usr/local/src/
RUN chmod +x /usr/local/src/entrypoint.sh
WORKDIR ${SRC}
ENTRYPOINT ["/usr/local/src/entrypoint.sh"]








`

I already used pip3 install -U bert-serving-server to install the component.

Thanks
weizhen

**Comment by weizhenzhao** [comment]
![image](https://user-images.githubusercontent.com/13706689/55583153-caede080-5753-11e9-9fb4-cd522ffe981e.png)
Is there something relative with the zmq connection in the docker?
for example the endpoint between different computer show be exposed out in the docker container?
because it find problem occurred between just few line codes above , and if these code go through and it show print out  already and listening

Thanks
weizhen

**Comment by weizhenzhao** [comment]
Dear hanxiao

I've made few change with the code , adding some log print , and install from the source
you can see the change in the following picture:
![捕获5](https://user-images.githubusercontent.com/13706689/55601688-a8c88280-5794-11e9-9ee2-95ba3d4b204c.PNG)

and in windows platform I can see the socket ip address and port clearly:
![捕获4](https://user-images.githubusercontent.com/13706689/55601716-c5fd5100-5794-11e9-8893-0477583f41a0.PNG)


but in the docker container , I can't see the socket ip address and the port:
![捕获3](https://user-images.githubusercontent.com/13706689/55601750-e9280080-5794-11e9-8978-8d7f001add48.PNG)

does it matter?

thanks
weizhen

**Comment by weizhenzhao** [comment]
@hanxiao 
Dear hanxiao

I find in the docker which line of code that cause long time and blocking here.
can you take a look?

![image](https://user-images.githubusercontent.com/13706689/55707485-441c5a80-5a16-11e9-8549-c5551492304c.png)

very appreciate for you

Thanks
weizhen

**Comment by hanxiao** [comment]
I personally can't reproduce this on docker with TF 1.10. I remember some people encountered this issue and solved it by using a specific version of tensorflow.

**Comment by weizhenzhao** [comment]
should I down grade to 1.10? currently I'm using tf 1.13.0

**Comment by weizhenzhao** [comment]
I find the problem . previously I always using the docker toolbox ,that tool isn't easy for specify the cpu numbers or memory , after I changing to the windows 10 pro system and installing the docker for windows tool . I can easily manage the cpu and the memory .

![image](https://user-images.githubusercontent.com/13706689/55732871-523a9d00-5a4f-11e9-9b64-f0a4fd863732.png)

and when executing the tf.import_graph_def method , task monitor shows that the io grows up to 99%
so that operation really cost the io resource and the memory , in the docker it show be more that 8GB memory for the computer to load that model .

it works
![image](https://user-images.githubusercontent.com/13706689/55733018-a180cd80-5a4f-11e9-8ca6-95c00409c39a.png)

thanks
weizhen

**Comment by pratikaher88** [comment]
@weizhenzhao Thanks a lot, I spent almost one day on this .
