### ISSUE TITLE
unrecognized arguments: -tuned_model_dir rasa_model_output

### ISSUE THREAD

**Issue by SLOCAT** [hanxiao/bert-as-service#323]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [ ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:
bert-serving-start -model_dir ./chinese_L-12_H-768_A-12/ -num_worker=4 -tuned_model_dir ./rasa_model_output/

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:
usage: bert-serving-start [-h] -model_dir MODEL_DIR [-max_seq_len MAX_SEQ_LEN]
                          [-num_worker NUM_WORKER]
                          [-max_batch_size MAX_BATCH_SIZE]
                          [-priority_batch_size PRIORITY_BATCH_SIZE]
                          [-port PORT] [-port_out PORT_OUT]
                          [-pooling_layer POOLING_LAYER [POOLING_LAYER ...]]
                          [-pooling_strategy {NONE,REDUCE_MAX,REDUCE_MEAN,REDUCE_MEAN_MAX,FIRST_TOKEN,LAST_TOKEN}]
                          [-cpu] [-xla] [-verbose]
                          [-gpu_memory_fraction GPU_MEMORY_FRACTION]
                          [-device_map DEVICE_MAP [DEVICE_MAP ...]] [-version]
bert-serving-start: error: unrecognized arguments: -tuned_model_dir ./rasa_model_output/

...

**Comment by hanxiao** [comment]
Version too old
```bash
pip install -U bert-serving-server bert-serving-client
```
