### ISSUE TITLE
Questions about function read_tokenized_examples() when handling sentence pair.

### ISSUE THREAD

**Issue by KaqiKaqi** [hanxiao/bert-as-service#326]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir=/workspace//chinese_L-12_H-768_A-12 -tuned_model_dir=/workspace//fine-tune-model -ckpt_name=model.ckpt-1865 -cpu -max_batch_size=16  -num_worker=1 -num_labels=2 -pooling_layer=-1 -pooling_strategy=CLASSIFICATION -max_seq_len=64
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode(['你好 ||| 你好呀'])
```
I rewrite graph.py according to another issue to serve an end2end sentence pair classification model.

The first question:
In extract_features.py, line 174 in function read_tokenized_examples(),  it seems text_b = ss[(j + 1):]  should be text_b = ss[(j + 3):], otherwise text_b starts with '|| '.

Another question : why should I put whitespace around '|||'?

For bc.encode(['你好 ||| 你好呀']), the probability for they being the same is 0.9906956; for bc.encode(['你好|||你好呀']) the probability is almost 0. So the white space does matter. But I can't figure it out by reading the code. 

Thanks a lot.

...

**Comment by hanxiao** [comment]
1. Sorry but you are wrong. `read_tokenized_examples` wont be called by default, it is only called when `bc.encode(..., is_tokenized=True)`

2. ` ||| ` (wrapped with white space) is a pattern that defines a sentence pair. If you don't wrap whitespace around `|||`, then the pattern fails and the service will consider the input as a single sentence, which explains your case.

**Comment by KaqiKaqi** [comment]
> * Sorry but you are wrong. `read_tokenized_examples` wont be called by default, it is only called when `bc.encode(..., is_tokenized=True)`. When `is_tokenized=True` your input should be whitespace separated, so in this case `ss[(j+1):]` makes totally sense.
> * `|||` (wrapped with white space) is a pattern that defines a sentence pair. If you don't wrap whitespace around `|||`, then the pattern fails and the service will consider the input as a single sentence, which explains your case.

Thanks a lot! I understand. : )

**Comment by hanxiao** [comment]
btw I realize there is a misinterpretation on my answer:
> When is_tokenized=True your input should be whitespace separated, so in this case ss[(j+1):] makes totally sense.

The correct one should be:

When `is_tokenized=True` each of your sentence should be a list of strings (rather than a single string), so in this case ss[(j+1):] makes totally sense. See example code at https://bert-as-service.readthedocs.io/en/latest/source/client.html#client.BertClient.encode
