### ISSUE TITLE
bc.encode(texts2, is_tokenized=True) doesn't work

### ISSUE THREAD

**Issue by berton820** [hanxiao/bert-as-service#327]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -show_tokens_to_client -device_map 1 -num_worker 1 -model_dir YOUR_SERVER_ARGS
```

and calling the server via:
```python
texts = ['你 好 嘛 ']
bc = BertClient(ip='xxx')
texts2 = [s.split() for s in texts]
vecs = bc.encode(texts2, is_tokenized=True)
vecs.shape

返回(1, 768)
```

Then this issue shows up:
我看介绍说返回的应该是每个token的embedding（https://github.com/hanxiao/bert-as-service#using-your-own-tokenizer）也就是返回的shape应该是[1, 25, 768]才对

![image](https://user-images.githubusercontent.com/28380536/56498232-62647900-6533-11e9-95b0-2d160a802041.png)

...

**Comment by hanxiao** [comment]
You need to set `-pooling_strategy NONE` on the server side if you want to get token-wise embeddings.

btw, I'm quite confused by your version of `bert-serving-server`. I assume you are showing your local `bert-serving-server` version whereas you are calling `bc.encode` to a remote `bert-serving-server`, which is 1.8.9. Otherwise, the client shall throw an exception.

**Comment by loretoparisi** [comment]
@hanxiao I'm a bit confused where actually the embedding is calculated within `bertserver`- is it here: https://github.com/hanxiao/bert-as-service/blob/master/server/bert_serving/server/graph.py#L99?
