### ISSUE TITLE
From where i can download 'README.md' for example8.py

### ISSUE THREAD

**Issue by Pem14604** [hanxiao/bert-as-service#335]
prefix_q = '##### **Q:** '
with open('README.md') as fp:
    questions = [v.replace(prefix_q, '').strip() for v in fp if v.strip() and v.startswith(prefix_q)]
    print('%d questions loaded, avg. len of %d' % (len(questions), np.mean([len(d.split()) for d in questions])))

**Comment by hanxiao** [comment]
https://github.com/hanxiao/bert-as-service/blob/master/README.md
