### ISSUE TITLE
zmq.error.ZMQError: Socket operation on non-socket

### ISSUE THREAD

**Issue by Irenehere** [hanxiao/bert-as-service#336]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x]  Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): conda
- TensorFlow version: 1.13.1
- Python version: 3.7.3
- `bert-as-service` version: 1.8.9 
---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bc = BertClient(port=6020, port_out=6021, show_server_config=True)
```

and calling the server via:
```python
   args = get_args_parser().parse_args(['-model_dir', '/home/gy/bert/uncased_L-24_H-1024_A-16',
                                             '-port', '6020',
                                             '-port_out', '6021',
                                             '-max_seq_len', '400',
                                             '-pooling_layer', "-"+str(pool_layer),
                                             '-mask_cls_sep',
                                             '-cpu'])
bc.encode()
```

Then this issue shows up:
Traceback (most recent call last):
  File "hyperparams_tuning2.py", line 93, in <module>
    embedding = bc.encode(text)
  File "/home/gy/anaconda3/envs/thesis/lib/python3.7/site-packages/bert_serving/client/__init__.py", line 204, in arg_wrapper
    self.receiver.setsockopt(zmq.RCVTIMEO, self.timeout)
  File "zmq/backend/cython/socket.pyx", line 424, in zmq.backend.cython.socket.Socket.set
  File "zmq/backend/cython/socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: Socket operation on non-socket

...

**Comment by Bennu-Li** [comment]
I have the same issue. Have you solved this problem.
