### ISSUE TITLE
calling BertClient in the example script hangs 

### ISSUE THREAD

**Issue by jennykim1016** [hanxiao/bert-as-service#349]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): pip install tensorflow==1.12
- TensorFlow version: 1.12
- Python version:
- `bert-as-service` version: 1.8
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```
python example/example1.py
```

and calling the server via:
```
python
bc = BertClient()
bc.encode()
```

Then this issue shows up:

bc=BertClient() never executes. If I type 

```
bert-serving-start -model_dir uncased_L-12_H-768_A-12 -num_worker=4 -cpu
```
though it prints out the following and hangs there. 

           ckpt_name = bert_model.ckpt
         config_name = bert_config.json
                cors = *
                 cpu = True
          device_map = []
  fixed_embed_length = False
                fp16 = False
 gpu_memory_fraction = 0.5
       graph_tmp_dir = None
    http_max_connect = 10
           http_port = None
        mask_cls_sep = False
      max_batch_size = 256
         max_seq_len = 25
           model_dir = uncased_L-12_H-768_A-12
          num_worker = 4
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556
       prefetch_size = 10
 priority_batch_size = 16
show_tokens_to_client = False
     tuned_model_dir = None
             verbose = False
                 xla = False

I:VENTILATOR:[__i:__i: 66]:freeze, optimize and export graph, could take a while...
I:GRAPHOPT:[gra:opt: 52]:model config: uncased_L-12_H-768_A-12/bert_config.json
I:GRAPHOPT:[gra:opt: 55]:checkpoint: uncased_L-12_H-768_A-12/bert_model.ckpt
I:GRAPHOPT:[gra:opt: 59]:build graph...
I:GRAPHOPT:[gra:opt:128]:load parameters from checkpoint...
I:GRAPHOPT:[gra:opt:132]:optimize...
I:GRAPHOPT:[gra:opt:140]:freeze...
I:GRAPHOPT:[gra:opt:145]:write graph to a tmp file: /tmp/tmppj4xiv2a
I:VENTILATOR:[__i:__i: 74]:optimized graph is stored at: /tmp/tmppj4xiv2a
I:VENTILATOR:[__i:_ru:128]:bind all sockets
I:VENTILATOR:[__i:_ru:132]:open 8 ventilator-worker sockets
I:VENTILATOR:[__i:_ru:135]:start the sink
I:SINK:[__i:_ru:303]:ready
I:VENTILATOR:[__i:_ge:219]:get devices
W:VENTILATOR:[__i:_ge:243]:no GPU available, fall back to CPU
I:VENTILATOR:[__i:_ge:252]:device map: 
		worker  0 -> cpu
		worker  1 -> cpu
		worker  2 -> cpu
		worker  3 -> cpu
I:WORKER-1:[__i:_ru:514]:use device cpu, load graph from /tmp/tmppj4xiv2a
I:WORKER-0:[__i:_ru:514]:use device cpu, load graph from /tmp/tmppj4xiv2a
I:WORKER-2:[__i:_ru:514]:use device cpu, load graph from /tmp/tmppj4xiv2a
I:WORKER-3:[__i:_ru:514]:use device cpu, load graph from /tmp/tmppj4xiv2a
I:WORKER-0:[__i:gen:542]:ready and listening!
I:WORKER-2:[__i:gen:542]:ready and listening!
I:WORKER-1:[__i:gen:542]:ready and listening!
I:WORKER-3:[__i:gen:542]:ready and listening!
I:VENTILATOR:[__i:_ru:163]:all set, ready to serve request!

(no command line interfacing popping up, it waits here)

Any idea what I should do to fix this error? I am trying to generate sentence embedding for 3000+ texts so being able to run the python script is essential. Thanks.

**Comment by jennykim1016** [comment]
Oops, sorry -- I haven't started the server and was running the script. My bad, closing the issue.

**Comment by wangru158105** [comment]
> Oops, sorry -- I haven't started the server and was running the script. My bad, closing the issue.

what do you mean"started the server"? i met the same problem
