### ISSUE TITLE
WARNING: This is a development server. Do not use it in a production deployment.

### ISSUE THREAD

**Issue by orkenstein** [hanxiao/bert-as-service#356]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mac OS X 10.14.4
- TensorFlow installed from (source or binary):
`pipenv install tensorflow`
- TensorFlow version:
1.13.1
- Python version:
3.7.3
- `bert-as-service` version: 
1.9.1
- GPU model and memory:
AMD Radeon R9 M370X 2 GB
Intel Iris Pro 1536 MB
- CPU model and memory:
2.5 GHz Intel Core i7
---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
pipenv run bert-serving-start -model_dir=data -tuned_model_dir=model -ckpt_name=model.ckpt-919 -http_port 8125
```

and calling the server via:
Not calling yet

Then this issue shows up:
```shell
I:WORKER-0:[__i:_ru:517]:use device cpu, load graph from /var/folders/sd/bvf_62ks4r1gfw97h40zpfyw0000gn/T/tmpj8r6_cs5
 * Serving Flask app "bert_serving.server.http" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:8125/ (Press CTRL+C to quit)
I:WORKER-0:[__i:gen:545]:ready and listening!
```

Not sure if its really an issue, but looks fragile.

**Comment by hanxiao** [comment]
That's true. For security concerns, you should not expose this service directly to the web, it's not optimized for security. You can at least containerize this service via docker.

btw, that warning is raised from `flask`, not from `bert-as-service`.

**Comment by orkenstein** [comment]
Ok. Docker is the way to go
