### ISSUE TITLE
Sentences pair classification tasks

### ISSUE THREAD

**Issue by Colanim** [hanxiao/bert-as-service#36]
I can use `bert-as-service` to encode each sentence one by one.
**Is it possible to use it to encode pair of sentences, as described in the official paper ?**

---

I want to do :
`bc.encode(['First do it ||| then do it right'])`

So I can have one single vectors for these 2 sentences :

> [CLS] First do it [SEP] then do it right [SEP]

**Comment by hanxiao** [comment]
currently no, but may be a good future feature.

**Comment by Colanim** [comment]
Isn't it already implemented ?

From `bert/extract_features.py`:

`def read_examples(lst_strs):
    """Read a list of `InputExample`s from a list of strings."""
    unique_id = 0
    for ss in lst_strs:
        line = tokenization.convert_to_unicode(ss)
        if not line:
            continue
        line = line.strip()
        text_a = None
        text_b = None
        m = re.match(r"^(.*) \|\|\| (.*)$", line)
        if m is None:
            text_a = line
        else:
            text_a = m.group(1)
            text_b = m.group(2)
        yield InputExample(unique_id=unique_id, text_a=text_a, text_b=text_b)
unique_id += 1`

**Comment by Colanim** [comment]
I've tried and it seems to work, I got correct results.
