### ISSUE TITLE
tf 2 support?

### ISSUE THREAD

**Issue by myshzzx** [hanxiao/bert-as-service#363]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x ] Are you running the latest `bert-as-service`?
* [ x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): win10 x64
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.0.0-alpha0
- Python version: 3.7.2
- `bert-as-service` version: 1.9.1
- GPU model and memory:   
- CPU model and memory:  
---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir L:\bert\chinese_L-12_H-768_A-12 -num_worker=4  -cpu
```

Then this issue shows up:

```
I:[35mVENTILATOR[0m:freeze, optimize and export graph, could take a while...
c:\program files\python37\lib\site-packages\bert_serving\server\helper.py:168: UserWarning: Tensorflow 2.0.0-alpha0 is not tested! It may or may not work. Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/
  'Feel free to submit an issue at https://github.com/hanxiao/bert-as-service/issues/' % tf.__version__)
E:[36mGRAPHOPT[0m:fail to optimize the graph!
Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\bert-serving-start.exe\__main__.py", line 9, in <module>
  File "c:\program files\python37\lib\site-packages\bert_serving\server\cli\__init__.py", line 4, in main
    with BertServer(get_run_args()) as server:
  File "c:\program files\python37\lib\site-packages\bert_serving\server\__init__.py", line 70, in __init__
    self.graph_path, self.bert_config = pool.apply(optimize_graph, (self.args,))
TypeError: cannot unpack non-iterable NoneType object
```

in fact the reason why subprocess fails is that tf.ConfigProto(server/graph.py line.44) be removed from tf 2.0. so would you support tf 2.0 in the future?

...

**Comment by tobegit3hub** [comment]
We has the similar issue when using TensorFlow 2.x because it uses the deprecated API of TensorFlow 1.x.

<img width="793" alt="Screenshot 2019-09-19 at 11 30 34 AM" src="https://user-images.githubusercontent.com/2715000/65211402-21b46000-dad1-11e9-98ef-410cce5221e4.png">

**Comment by isabeauoliveri** [comment]
same problem

**Comment by ayxemma** [comment]
same problem. using tf_upgrade_v2 to upgrade code does not solve problem
