### ISSUE TITLE
Concatenated pooling_layers alter the embeddings compared to single layer output

### ISSUE THREAD

**Issue by dhruvsakalley** [hanxiao/bert-as-service#367]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ x] Are you running the latest `bert-as-service`?
* [ x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon Linux (4.14.97-74.72.amzn1.x86_64)
- TensorFlow installed from (source or binary): conda tensorflow environment
- TensorFlow version: 1.13
- Python version: 3.7
- `bert-as-service` version: bert-serving-server==1.9.1
- GPU model and memory: none
- CPU model and memory: AMD EPYC 7571, 32 GB
---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir=./bert_models/cased_L-24_H-1024_A-16-700k/ -num_worker=1 -http_port 8125 -max_seq_len=NONE  -pooling_layer -4 -3 -2 -1 -cpu

and
bert-serving-start -model_dir=./bert_models/cased_L-24_H-1024_A-16-700k/ -num_worker=1 -http_port 8125 -max_seq_len=NONE -pooling_layer -1 -cpu
```

and calling the server via:
curl -X POST <elb-dns> -H 'content-type: application/json' -d '{"id": 123,"texts": ["hello world"], "is_tokenized": false}'

Then this issue shows up:
When the service is launched to return concatenated layers -4 -3 -2 -1, the returned result is of shape (4096,). The result[0] is reshaped to 1024x4 dimensions, none of the resulting layers pass numpy.array_equal to the output of the service with just a single layer [-1].
Question:
Does the concatenation alter the resulting embeddings in a way that works differently based on the number of layers returned by the service? If not is there an alternative to reshape the output concatenated layers differently to be identical to a single layer return?
...

**Comment by rpoli40** [comment]
I see the same issue. Please respond

**Comment by dhruvsakalley** [comment]
I figured out the mistake I was using reshape and it was giving me wrong vectors, instead used split to get the concatenated layers back.
pooling_layers = np.split(embeddings_4321, 4, axis=0)
further to calculate mean used this: 
mean4321 =  np.mean(pooling_layers, axis=0)
