### ISSUE TITLE
ValueError: Could not find trained model in model_dir: /tmp/tmp_st5oe05

### ISSUE THREAD

**Issue by titicaca** [hanxiao/bert-as-service#38]
Has the service been started up correctly? Why is it using an temporary folder as I have already indicated a model_dir in params? 

WARNINGs are shown as follows:

```
usage: app.py -model_dir /tmp/bert/chinese_L-12_H-768_A-12 -num_worker=1
                 ARG   VALUE
__________________________________________________
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /tmp/bert/chinese_L-12_H-768_A-12
          num_worker = 1
       pooling_layer = -2
    pooling_strategy = REDUCE_MEAN
                port = 5555

WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmp_st5oe05
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f80e7184598>) includes params argument, but params are not passed to Estimator.
I:WORKER-2:[ser:run:227]:ready and listening
Process BertWorker-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/xxx/workspace/github/bert-as-service/service/server.py", line 229, in run
    for r in self.estimator.predict(input_fn, yield_single_examples=False):
  File "/home/xxx/pyenv/ternary/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 488, in predict
    self._model_dir))
ValueError: Could not find trained model in model_dir: /tmp/tmp_st5oe05.
```

**Comment by lrjocean** [comment]
the same problem

**Comment by EricLingRui** [comment]
I have encountered the same problem, change the path to this：./tmp/tmp_st5oe05 may solve your problem.

**Comment by KevinChen1994** [comment]
> I have encountered the same problem, change the path to this：./tmp/tmp_st5oe05 may solve your problem.

But I don't have the path named ./tmp. Every time I run app.py, it will create two tempfile, in those file only have a socket file

**Comment by hanxiao** [comment]
You may see a warning message like `Could not find trained model in model_dir: /tmp/tmpuB5g5c, running initialization to predict.` This message is expected, it just means that we are using the init_from_checkpoint() API rather than the saved model API. It's a tensorflow behavior.

**Comment by titicaca** [comment]
> You may see a warning message like `Could not find trained model in model_dir: /tmp/tmpuB5g5c, running initialization to predict.` This message is expected, it just means that we are using the init_from_checkpoint() API rather than the saved model API. It's a tensorflow behavior.
> 
> Besides this warning, you should be able to run service after specifying a valid `python app.py -model_dir`, if you still face the problem, please let me know.

Thanks for the reply. I just ignored the warnings, but it still didn't work. I started the service on CentOS 7, and tried to execute the client apis, but it was stuck and had no responses. Did I miss something?  The codes are shown as follows:

Server side
```
usage: app.py -model_dir=/tmp/bert/chinese_L-12_H-768_A-12 -num_worker=1
                 ARG   VALUE
__________________________________________________
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /tmp/bert/chinese_L-12_H-768_A-12
          num_worker = 1
       pooling_layer = -2
    pooling_strategy = REDUCE_MEAN
                port = 5555

WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpk49dbrch
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7fb20e35a598>) includes params argument, but params are not passed to Estimator.
I:WORKER-2:[ser:run:227]:ready and listening
Process BertWorker-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/fangzhou/workspace/github/bert-as-service/service/server.py", line 229, in run
    for r in self.estimator.predict(input_fn, yield_single_examples=False):
  File "/home/fangzhou/pyenv/ternary/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 488, in predict
    self._model_dir))
ValueError: Could not find trained model in model_dir: /tmp/tmpk49dbrch.
```

Client Side, no response
```
>>> bc = BertClient()
the server at localhost:5555 returns the following config:
                      ipc_sink  =       ipc://tmptzmgqG/socket
                python_version  =       3.6.3 (default, Jan  4 2018, 16:40:53)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
            tensorflow_version  =       1.8.0
                   ipc_backend  =       ipc://tmpWXaVhP/socket
                max_batch_size  =       256
                          port  =       5555
                   max_seq_len  =       25
                        client  =       36109636-d435-4307-aaa0-3f16f3b16f9c
                     model_dir  =       /tmp/bert/chinese_L-12_H-768_A-12
                   server_time  =       2018-11-23 09:11:37.716187
                   num_process  =       2
                    num_worker  =       1
you should NOT see this message multiple times! if you see it appears repeatedly, please consider moving "BertClient()" out of the loop.
>>> bc.encode(['First do it', 'then do it right', 'then do it better'])
```

**Comment by KevinChen1994** [comment]
My problem is not solved.

> usage: app.py -model_dir=./tmp/tmppclqiu4 -num_worker=4
>                  ARG   VALUE
> __________________________________________________
>       max_batch_size = 256
>          max_seq_len = 25
>            model_dir = ./tmp/tmppclqiu4
>           num_worker = 4
>        pooling_layer = -2
>     pooling_strategy = REDUCE_MEAN
>                 port = 5555
> 
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/home/chenmeng/anaconda3/envs/python36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "/home/chenmeng/project/bert-as-service/service/server.py", line 92, in run
>     process = BertWorker(i, self.args, backend_addr, sink_thread.address)
>   File "/home/chenmeng/project/bert-as-service/service/server.py", line 193, in __init__
>     self.tokenizer = tokenization.FullTokenizer(vocab_file=self.vocab_fp)
>   File "/home/chenmeng/project/bert-as-service/bert/tokenization.py", line 115, in __init__
>     self.vocab = load_vocab(vocab_file)
>   File "/home/chenmeng/project/bert-as-service/bert/tokenization.py", line 77, in load_vocab
>     token = convert_to_unicode(reader.readline())
>   File "/home/chenmeng/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 178, in readline
>     self._preread_check()
>   File "/home/chenmeng/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
>     compat.as_bytes(self.__name), 1024 * 512, status)
>   File "/home/chenmeng/anaconda3/envs/python36/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
>     c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.NotFoundError: ./tmp/tmppclqiu4/vocab.txt; No such file or directory

**Comment by wqxu** [comment]
I met the same problem while I was using tensorflow 1.8.0, and when I upgraded tensorflow to 1.12.0, the problem solved.

**Comment by hanxiao** [comment]
tf 1.10 is the minimum requirement as written in README.md, thanks @wqxu for making it clear again.

please upgrade your tensorflow.
