### ISSUE TITLE
Error with Stop BertServer from Python

### ISSUE THREAD

**Issue by lu161513** [hanxiao/bert-as-service#394]
My Code:

`from bert_serving.server.helper import get_args_parser`
`from bert_serving.server import BertServer`
`from bert_serving.client import BertClient`

`args = get_args_parser().parse_args(['-model_dir', '/home/cn-pvgtoddlu/model/chinese_L-12_H-768_A-12',
                                     '-num_worker','1',
                                     '-port', '5555',
                                     '-port_out', '5556',
                                     '-max_seq_len', 'NONE',
                                     '-mask_cls_sep',
                                     '-cpu'])`
`server = BertServer(args)`
`print("bert server start....")`
`server.start()`

`bc = BertClient(port=5555,port_out=5556)`
`result = bc.encode(['First do it', 'then do it right', 'then do it better'])`

`print(result)`

`BertServer.shutdown(port=5555)`
`print("bert server stop....")`

Error:
`Traceback (most recent call last):`
  `File "<input>", line 1, in <module>`
  `File "/home/cn-pvgtoddlu/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script`
  `File "/home/cn-pvgtoddlu/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile`
    `exec(compile(contents+"\n", file, 'exec'), glob, loc)`
  `File "/home/cn-pvgtoddlu/tmp/pycharm_project_815/AI_Factory_Core/component/word_embedding/extract_embedding.py", line 21, in <module>`
    `BertServer.shutdown(port=5555)`
`TypeError: shutdown() got an unexpected keyword argument 'port'`

**args** of staticmethod shutdown are not from parser i think.

shutdown function:
`@staticmethod`
    `def shutdown(args):`
        `with zmq.Context() as ctx:`
            `ctx.setsockopt(zmq.LINGER, args.timeout)`
            `with ctx.socket(zmq.PUSH) as frontend:`
                `try:`
                    `frontend.connect('tcp://%s:%d' % (args.ip, args.port))`

**Comment by lu161513** [comment]
I think it should be :

shut_args = get_shutdown_parser().parse_args(['-ip','localhost','-port','5555','-timeout','5000'])
BertServer.shutdown(shut_args)

**Comment by lu161513** [comment]
我可以修正这个，可以merge进去吗~

**Comment by hanxiao** [comment]
Welcome for your contribution. Simply make a pull request and I will approve it. Thanks

**Comment by bartala** [comment]
Don't forget to add:
from bert_serving.server.helper import get_shutdown_parser

**Comment by chengyu-liu-cs** [comment]
But I got unrecognized timeout and -ip

args = get_args_parser().parse_args(['-model_dir', '/bert/bert-base-cased-v1/', '-port', '5555', '-cpu', '-ip','localhost', '-timeout','5000'])
usage:  [-h] -model_dir MODEL_DIR [-tuned_model_dir TUNED_MODEL_DIR]
        [-ckpt_name CKPT_NAME] [-config_name CONFIG_NAME]
        [-graph_tmp_dir GRAPH_TMP_DIR] [-max_seq_len MAX_SEQ_LEN]
        [-cased_tokenization]
        [-pooling_layer POOLING_LAYER [POOLING_LAYER ...]]
        [-pooling_strategy {NONE,REDUCE_MAX,REDUCE_MEAN,REDUCE_MEAN_MAX,FIRST_TOKEN,LAST_TOKEN}]
        [-mask_cls_sep] [-no_special_token] [-show_tokens_to_client]
        [-no_position_embeddings] [-port PORT] [-port_out PORT_OUT]
        [-http_port HTTP_PORT] [-http_max_connect HTTP_MAX_CONNECT]
        [-cors CORS] [-num_worker NUM_WORKER] [-max_batch_size MAX_BATCH_SIZE]
        [-priority_batch_size PRIORITY_BATCH_SIZE] [-cpu] [-xla] [-fp16]
        [-gpu_memory_fraction GPU_MEMORY_FRACTION]
        [-device_map DEVICE_MAP [DEVICE_MAP ...]]
        [-prefetch_size PREFETCH_SIZE] [-fixed_embed_length] [-verbose]
        [-version]
: error: unrecognized arguments: -ip localhost -timeout 5000
