### ISSUE TITLE
support cpu?

### ISSUE THREAD

**Issue by Jie-Yuan** [hanxiao/bert-as-service#41]

**Comment by hanxiao** [comment]
yes. client-side for sure support GPU and CPU-only.
Server side supports CPU since #4 . You can run it on CPU without any problem.
Note the server doesn't supports GPU+CPU, or no available GPU thus back-off to CPU, though shouldn't be hard to support it.

**Comment by burongjiashe** [comment]
"no available GPU thus back-off to CPU". How to support it?
