### ISSUE TITLE
client-side python2 encoding error

### ISSUE THREAD

**Issue by hanxiao** [hanxiao/bert-as-service#42]
server python3; client python 2; will break the server because of the encoding error.

**Comment by hhxx2015** [comment]
`Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from service.server import BertServer
  File "/mnt/haohhxx/e/code/python3workspace/bert-as-service/service/server.py", line 101
    jsonapi.dumps({**{'client': client.decode('ascii'),
                    ^
SyntaxError: invalid syntax
`

just like this ？
