### ISSUE TITLE
Dependency between sentences embeddings within request

### ISSUE THREAD

**Issue by Colanim** [hanxiao/bert-as-service#43]
I run this code :

```
bc = BertClient()
a = bc.encode['hey you', 'hey you']
b = bc.encode['hey you']
c = bc.encode['hey you']
```

---

If I compare `b` and `c`, these are the same :

`print((b == c).all())`

> True

This is expected behavior

---

**But why `a[0]` and `a[1]` are not the same ?**

`print((a[0] == a[1]).all())`

> False

I would expect them to have the same embeddings.

**Comment by hanxiao** [comment]
they are same, to certain extent (i.e. precision)
note, you should always tolerate some jitter when doing numerical comparison like this.
e.g.
```python
(abs(a[0] - a[1])<1e-6).all()
```
