### ISSUE TITLE
run on GPU?

### ISSUE THREAD

**Issue by chaochaoSZ** [hanxiao/bert-as-service#441]
Why I can't run on GPU although the server run on GPU?

**Comment by ZhaoWang-IIT** [comment]
I have the same confusion. It seems that:
<1> When I start the server with the command "bert-serving-start", **the bertServer is using GPU**. 
<2> But when I use bertClient to encode sentences, **the bertClient is not using GPU**. 
Can anybody explain this? Is this package "bert-as-service" designed to run like this?
