### ISSUE TITLE
client don't receive result

### ISSUE THREAD

**Issue by DerekBin** [hanxiao/bert-as-service#45]
client b'8986ca10-6d73-4de6-9895-6d8beab68e11' 3 samples are done! sending back to client

you should NOT see this message multiple times! if you see it appears repeatedly, please consider moving "BertClient()" out of the loop.

**Comment by Colanim** [comment]
Can you show a bit more of your code, in client side ? How do you call encode for  example and how do you print the result might help

**Comment by DerekBin** [comment]
This is my client code:
from service.client import BertClient
bc = BertClient(ip='192.168.0.102', port=5555)
bc.encode(['First do it', 'then do it right', 'then do it better'])

print(bc)

**Comment by Colanim** [comment]
It should be :

```
from service.client import BertClient
bc = BertClient(ip='192.168.0.102', port=5555)
vectors = bc.encode(['First do it', 'then do it right', 'then do it better'])

print(vectors)
```

**Comment by DerekBin** [comment]
ok, thank you
