### ISSUE TITLE
bert encode()在unbuntu上发生进程挂起的问题

### ISSUE THREAD

**Issue by ares5221** [hanxiao/bert-as-service#454]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ ] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution Linux Ubuntu 18.04):
- TensorFlow installed from (source or binary):source
- TensorFlow version:1.12
- Python version:3.6
- `bert-as-service` version: 
- GPU model and memory:
- CPU model and memory:

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS worker=4
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:
在linux对20w条语句做encode（），执行到1.5w或者2w多以后，进程就停止了，但是没有发现OOM的提示，系统资源显示也没有耗尽，有人遇到这种情况吗？没有找到原因
...

**Comment by gmftbyGMFTBY** [comment]
I have the same question

**Comment by ares5221** [comment]
> I have the same question. But sometimes it works fine, and I cannot troubleshooting these issue.

yes, and it not happend in my win10 OS, only in unbuntu

**Comment by gmftbyGMFTBY** [comment]
Seems that #389 fixed the issue, but I'm not sure

**Comment by gmftbyGMFTBY** [comment]
I try to update the `bert-serving-server` and `bert-serving-client` to version `1.9.8` and it seems to be fine for me.
I suggest you to update your `bert-as-service`.

```python
# my env: python 3.6, ubuntu 18.04
pip install -U bert-serving-server bert-serving-client
```

**Comment by ares5221** [comment]
> I try to update the `bert-serving-server` and `bert-serving-client` to version `1.9.8` and it seems to be fine for me.
> I suggest you to update your `bert-as-service`.
> 
> ```python
> # my env: python 3.6, ubuntu 18.04
> pip install -U bert-serving-server bert-serving-client
> ```

ok，i will try it ,thks.

**Comment by superman-hulin** [comment]
请问这个问题解决了吗 我也有同样的问题

**Comment by ares5221** [comment]
> 请问这个问题解决了吗 我也有同样的问题

update bert as service

**Comment by superman-hulin** [comment]
> 
> 
> > 请问这个问题解决了吗 我也有同样的问题
> 
> update bert as service

thanks
