### ISSUE TITLE
Not able to pass value to boolean arguments 

### ISSUE THREAD

**Issue by ZhaoWang-IIT** [hanxiao/bert-as-service#455]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`? 
My version: 1.9.6

* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?

* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?

* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir ./BERT/uncased_L-24_H-1024_A-16/ -num_worker=4 -max_seq_len=30  -pooling_strategy=NONE  -show_tokens_to_client=True
```
and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode(['hello world!', 'this is it'], show_tokens=True)
```

Then this issue shows up on server side:
**bert-serving-start: error: argument -show_tokens_to_client: ignored explicit argument 'True'**
...
I tried different ways to set the argument and none of them worked:

- -show_tokens_to_client=True
- -show_tokens_to_client=true
- -show_tokens_to_client='True'
- -show_tokens_to_client='true'
- -show_tokens_to_client True
- -show_tokens_to_client true
- -no-show_tokens_to_client

**Besides this parameter (-show_tokens_to_client), I have the same issue with all other boolean parameters:**
-cpu
-xla
-fp16

I checked the source code and googled for this issue, but still have no idea of how to fix it. 
![image](https://user-images.githubusercontent.com/13983910/65826208-62854500-e246-11e9-9822-9c03043e9b42.png)

Does anybody encounter the same problem?

**Comment by hanxiao** [comment]
it's a flag, it should not be used with true/false. With it then it is true, without it then it is false.

`-show_tokens_to_client` that's it.

**Comment by ZhaoWang-IIT** [comment]
Thanks for the explanation, I tried "-show_tokens_to_client" and it worked.
