### ISSUE TITLE
same query, why i got different vectors from different serve with same model

### ISSUE THREAD

**Issue by ziyaochen** [hanxiao/bert-as-service#474]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [ yes] Are you running the latest `bert-as-service`?
* [ yes] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [ yes] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [yes ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
mac os
- TensorFlow installed from (source or binary):
source 
- TensorFlow version:
1.13.1
- Python version:
3.7.3
- `bert-as-service` version: 
latest
- GPU model and memory:
- CPU model and memory:

---

### Description
My start CMD:
bert-serving-start -model_dir ./57zh/ -num_worker=2

i get vectors from 
```python
bc = BertClient()
print(bc.encode(['你好']))
```
![image](https://user-images.githubusercontent.com/22961946/67863197-674b5a80-fb5e-11e9-8273-6b9367154922.png)

but when i stop the serve and restart serve with the same model,  i get different vectors
from  
```python
bc = BertClient()
print(bc.encode(['你好']))
```
![image](https://user-images.githubusercontent.com/22961946/67863275-919d1800-fb5e-11e9-9cc8-706429e09dd6.png)

everytime i restart the serve, i got different vectors from “你好”

...

**Comment by sxdxfan** [comment]
Please check if layer names are identical for tvars and init_vars in `get_assignment_map_from_checkpoint` function (`server/bert/modeling.py`)

**Comment by ziyaochen** [comment]
> Hi!
> It seems that your model weights are not loaded correctly.
> Please check if layer names are identical for `tvars` and `init_vars` in `get_assignment_map_from_checkpoint` function (`server/bert/modeling.py`)

that's  the problem, thanks

**Comment by ziyaochen** [comment]
solved

**Comment by xeisberg** [comment]
@sxdxfan , @zychen-real 
I beg your pardon for asking, but could you specify how to check if the layer names are identical given the following code?

def get_assignment_map_from_checkpoint(tvars, init_checkpoint):
    """Compute the union of the current variables and checkpoint variables."""
    assignment_map = {}
    initialized_variable_names = {}

    name_to_variable = collections.OrderedDict()
    for var in tvars:
        name = var.name
        m = re.match("^(.*):\\d+$", name)
        if m is not None:
            name = m.group(1)
        name_to_variable[name] = var

    init_vars = tf.train.list_variables(init_checkpoint)

    assignment_map = collections.OrderedDict()
    for x in init_vars:
        (name, var) = (x[0], x[1])
        if name not in name_to_variable:
            continue
        assignment_map[name] = name
        initialized_variable_names[name] = 1
        initialized_variable_names[name + ":0"] = 1

    return (assignment_map, initialized_variable_names)
