### ISSUE TITLE
BertClient with Multiprocessing stuck at waiting for req id

### ISSUE THREAD

**Issue by owenljn** [hanxiao/bert-as-service#480]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): https://github.com/tensorflow/tensorflow
- TensorFlow version: 1.14.0
- Python version: 3.7
- `bert-as-service` version: 1.9.8
- GPU model and memory: 4xRTX2080Ti 11GB
- CPU model and memory: 2xIntel Xeon Silver 4216, 512GB memory

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start -model_dir /multilinguual_L-12_H-768_A-12 -port 6555 -port_out 6556 -num_worker 2
```

and calling the server via:
```python
bc = BertClient(port=6555, port_out=6556)
bc.encode('Bonjour')
```
Requests are distributed to multiple CPU workers(multiprocessing mechanism to handle multiple requests simultaneously) and then sent to the same BertClient object,  however, BertClient is stuck at bc.encode() function. By looking into the code deeper, I found **it's stuck at line 146 of bert_serving/client/__init__.py** it somehow keeps waiting for the request id in the while loop.

If I send one request at a time, then BertClient is called once at a time, and it works perfectly fine, so I guess maybe it's caused by the multiprocessing mechanism??

Did anyone else have this issue? How did you solve it?
...

**Comment by rbagd** [comment]
Have you tried using the concurrent one, i.e?

```from bert_serving.client import ConcurrentBertClient as BertClient``` ?

**Comment by owenljn** [comment]
> 
> 
> Have you tried using the concurrent one, i.e
> 
> `from bert_serving.client import ConcurrentBertClient as BertClient` ?

Thank you for the reply.

I just tried it, still the same problem

**Comment by owenljn** [comment]
I fixed this problem by initiating BertClient for every worker in the Multi-process, this way, all BertClients are clones of the original one, and no worker is using the original BertClient at all.
