### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by lovasoa** [hanxiao/bert-as-service#50]
It would be nice to be able to depend on this library directly from [pipy](https://pypi.org).
Ideally, there would be two packages published: one for the client (without a dependency to tensorflow) and one for the server.

**Comment by hanxiao** [comment]
will do

**Comment by hanxiao** [comment]
fyi, this is issue is fixed. `bert-serving` is now available on pypi. with separate server and client packages. check latest readme for details.
