### ISSUE TITLE
Can I specify the service uses the specified GPU?

### ISSUE THREAD

**Issue by KevinChen1994** [hanxiao/bert-as-service#51]
My machine has 4 GPUs, When start the server, it will run on the 4 GPUs at the same time. But I still need GPU to run other code, So can I specify the service only run on the 1 specified GPU?
BTW, I tried use 'CUDA_VISIBLE_DEVICES='0' ' when I run the server, it did't work.
thanks!

**Comment by hanxiao** [comment]
`python app.py -num_worker=1`

details: https://github.com/hanxiao/bert-as-service#server-side-configs

**Comment by MrTuo** [comment]
But it can only controls the number of gpu to use, but not the specific gpu to use. I tried CUDA_VISIBLE_DEVICES too, it didn't work. Can you add an argument to specify the service in server-side? It is really important to me. Thanks :)

**Comment by hanxiao** [comment]
fyi, this issue was fixed in #137 and the feature is available since 1.5.8, please do
```bash
pip install -U bert-serving-server bert-serving-client
```
More info see: https://github.com/hanxiao/bert-as-service#q-can-i-specify-which-gpu-to-use
