### ISSUE TITLE
keyError on server side, 

### ISSUE THREAD

**Issue by tiru1930** [hanxiao/bert-as-service#52]
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/epbot/pipeline/bert-as-service/service/server.py", line 168, in run
    self.client_checksum[client_id]))
KeyError: b'edaf95b1-7d24-4012-bdb7-881b0fdf654c'

After this no more requests are accepting by Server, not able to debug, can you any please help on this.

is this error comes because of less resources , I,e CPU cores (my system cpu cores are busy with other  jobs)

**Comment by hanxiao** [comment]
this may be some bug of multi-threading in previous `BertServer`.
please checkout the latest master or try the release v1.2 and see if the problem is still there.
