### ISSUE TITLE
当BERT模型层数减少时zmq框架成为性能瓶颈

### ISSUE THREAD

**Issue by shuangt** [hanxiao/bert-as-service#524]
**Prerequisites**
3层的BERT模型和6层的BERT模型使用bert-as-service推理耗时一样，但直接使用自己的实验裸跑：3层BERT模型推理速度是6层的2倍。当BERT模型层数减少时zmq框架成为性能瓶颈。

> Please fill in by replacing `[ ]` with `[x]`.

* [ x] Are you running the latest `bert-as-service`?
* [x ] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x ] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [ ] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**
显卡：V100*8，启动4个worker

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): centos 7.7
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14
- Python version: 3.65
- `bert-as-service` version: 1.10
- GPU model and memory: 32GB
- CPU model and memory: 至强系列，312GB

---

### Description

> Please replace `YOUR_SERVER_ARGS` and `YOUR_CLIENT_ARGS` accordingly. You can also write your own description for reproducing the issue.

I'm using this command to start the server:

```bash
bert-serving-start YOUR_SERVER_ARGS
```

and calling the server via:
```python
bc = BertClient(YOUR_CLIENT_ARGS)
bc.encode()
```

Then this issue shows up:

...

**Comment by hanxiao** [comment]
not sure if your conclusion is valid, please refer to this benchmark

https://github.com/hanxiao/bert-as-service#speed-wrt-pooling_layer
