### ISSUE TITLE
如何将句向量维度从768降到128

### ISSUE THREAD

**Issue by XGodLike** [hanxiao/bert-as-service#536]
我的场景是两个文本的相似度，思路是：微调后，抽取的最后一层池化作为了句向量，用余弦来计算相似度。是768维的，效果还可以，后来因为有个需求需要降低到128维，我直接在768维后面接了一个全连接降到128维了。但是效果就不好了....是不是这种方式不可行？

**Comment by 57n** [comment]
把所有句子向量集合起來做奇異值分解(SVD)降到128維試看看呢？

**Comment by TheBestHu** [comment]
试试PCA 和 SVD
