### ISSUE TITLE
已安装Tensorflow2.0gpu，启动bert-as-service却提示no module named tensorflow

### ISSUE THREAD

**Issue by tianhongkang** [hanxiao/bert-as-service#550]
![image](https://user-images.githubusercontent.com/55080008/81682731-a6505600-9487-11ea-81bc-67a4d87a65d9.png)
![image](https://user-images.githubusercontent.com/55080008/81682772-b5370880-9487-11ea-907c-053704c9bcbe.png)

**Comment by hanxiao** [comment]
unrelated, check your system setup

**Comment by Elfsong** [comment]
I reckon that a lot of people meet this problem.
