### ISSUE TITLE
ModuleNotFoundError: No module named 'bert_serving.client' but I have installed them!

### ISSUE THREAD

**Issue by RuiqingGao** [hanxiao/bert-as-service#556]
![image](https://user-images.githubusercontent.com/31022412/83321762-7fb25d80-a284-11ea-8d94-e3987b2cfc61.png)
I have installed the modules, but when using them, I got the following problem.
![image](https://user-images.githubusercontent.com/31022412/83321782-b38d8300-a284-11ea-8d82-46e2241e0c85.png)
 system: Linux version 3.10.0-1062.9.1.el7.x86_64,
python 3.6.8

**Comment by hanxiao** [comment]
your python and system config problem, out of scope.

**Comment by milind29** [comment]
I have installed it but still got this error. Can anyone help?

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-66-166c53ca0c78> in <module>
      1 # import sys
----> 2 from bert_serving.client import BertClient
      3 client = BertClient()
      4 vectors = client.encode(['dog'],['cat'],['man'])

ModuleNotFoundError: No module named 'bert_serving'

**Comment by user-jianjian** [comment]
> your python and system config problem, out of scope.



> I have installed it but still got this error. Can anyone help?
> 
> ModuleNotFoundError Traceback (most recent call last) in 1 # import sys ----> 2 from bert_serving.client import BertClient 3 client = BertClient() 4 vectors = client.encode(['dog'],['cat'],['man'])
> 
> ModuleNotFoundError: No module named 'bert_serving'

got the same problem

**Comment by JoanFM** [comment]
Hey @user-jianjian ,

Have u updated the version to `clip-as-a-service`?
