### ISSUE TITLE
help with understanding REDUCE_MAX?

### ISSUE THREAD

**Issue by vr25** [hanxiao/bert-as-service#557]
Hi,

I was able to install and create sentence embedding. I am trying to understand the idea behind REDUCE_MAX. Can you please elaborate on it more?

I understand REDUCE_MEAN which averages the layers mentioned in the -pooling_layer argument. Say, for instance, I say -4 -3 -2 -1 REDUCE_MEAN, then it averages across the last four layers for all words in a sentence to create a sentence embedding. I don't quite follow this strategy for REDUCE_MAX. How to find the max values?

Thanks!

**Comment by vr25** [comment]
As per PyTorch doc [here](https://pytorch.org/docs/master/generated/torch.max.html?highlight=torch%20max#torch.max), I think I follow the max operation wherein it selects the maximum value along each dimension.

**Comment by hanxiao** [comment]
feel free to read the source code
