### ISSUE TITLE
As you say,the pooling strategy is REDUCE_MEAN.But in my case，it is not.Is it a bug?

### ISSUE THREAD

**Issue by Ningshiqi** [hanxiao/bert-as-service#558]
I want to get the sentence vector.
when the query is “普工”，and “普工普工” ，but the vector of two is not the same.
If the pooling strategy is reduce_mean,the two should have the same embedding.
Is there someting wrong

**Comment by hanxiao** [comment]
yes, your understanding about contextual embedding is wrong. I'd suggest you first read BERT paper before using this package.

**Comment by Ningshiqi** [comment]
Thank for your anwser.I don't consider the postion embedding.

**Comment by Ningshiqi** [comment]
> yes, your understanding about contextual embedding is wrong. I'd suggest you first read BERT paper before using this package.

Thank for your anwser.I don't consider the postion embedding.
