### ISSUE TITLE
TypeError: predict() got an unexpected keyword argument 'yield_single_examples'

### ISSUE THREAD

**Issue by yiyinianhua** [hanxiao/bert-as-service#58]
i met a problem in run app.py,use the lastest version 1.2

WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpf4r5hknt
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7f78dd079e18>) includes params argument, but params are not passed to Estimator.
I:WORKER-0:[ser:run:265]:ready and listening
Process BertWorker-2:
Traceback (most recent call last):
  File "/home/work/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/work/bert-as-service-1.2/service/server.py", line 267, in run
    for r in self.estimator.predict(input_fn, yield_single_examples=False):
TypeError: predict() got an unexpected keyword argument 'yield_single_examples'

**Comment by hanxiao** [comment]
tf 1.2 is not supported, please make sure your tensorflow >= 1.10
