### ISSUE TITLE
Other Encoding block will be released ?

### ISSUE THREAD

**Issue by Colanim** [hanxiao/bert-as-service#59]
As you linked your [blog](https://hanxiao.github.io/2018/06/24/4-Encoding-Blocks-You-Need-to-Know-Besides-LSTM-RNN-in-Tensorflow/#pooling-block) in the README, I read it : it was so interesting !! Thanks for sharing it.

---

Now, the main pooling strategies are `REDUCE_MEAN` and `REDUCE_MAX`, as described in the first part of your blog.

**Are you going to release other Sequence encoding blocks ?**

---

If I understood well, it seems difficult because others strategies are based on CNN, which needs data to train on. (Am I right ?)

**Comment by hanxiao** [comment]
Yes, other pooling blocks need additional training. Note, starting from 1.5.5 `bert-as-service` freezes and optimizes the graph during preprocessing and thus can be considered as a *feed-forward-only* library, which concentrates only on the inference stage.

Support training in `bert-as-service` is not my priority now. One exception is dimensionality reduction (mentioned in #62 ), one could train a 768-64-768 MLP on top with L1/L2 loss fairly easy.  This could be a next feature.
