### ISSUE TITLE
Can I set the size of sentence vectors?

### ISSUE THREAD

**Issue by shilan910** [hanxiao/bert-as-service#62]
"In general, each sentence is translated to a 768-dimensional vector." If I need 256-dimensional vector, how to get it？

**Comment by Colanim** [comment]
**You cannot change this.**

This is from the architecture of the BERT model itself. For example, for `BERT-Base, uncased` :
> 12-layer, **768-hidden**, 12-heads, 110M parameters

---

If you **really** need a 256-dimensional vector, you have to train from scratch your own BERT architecture.

**Comment by hanxiao** [comment]
no, because the number of hidden units is predefined. if you are using BERT model released by Google, then the number of hidden units is either 768 or 1024. 

if you want 256-dimensional vector, either add a `dense(num_units=256)` then train on some downstream task, or do subsampling directly in the feature space (make sense if your goal is to build a random forest).

**Comment by zysNLP** [comment]
"if you want 256-dimensional vector, either add a dense(num_units=256) then train on some downstream task, or do subsampling directly in the feature space (make sense if your goal is to build a random forest)"
As you talked about reducing dimensions above. Can you explain the solution in detail? "Add a dense",what does that mean? Where can we connect the dense like this? Also the sentence you said: "subsampling directly in the feature space ",I don't quite understand this, could you explain it in a little more detail?

**Comment by feiyuchen7** [comment]
"So I try to search for answers to reduce the 768-dimensions or any other useful solution under the condition that cannot change computer reccently"
@zysNLP  Hi I got this problem as well(768 too large) and i am looking for a method reducing it to 256. I'm wondering that how did you fix it? Thanks a lot!

**Comment by yuchenlin** [comment]
maybe you might want do a simple PCA to do the dimension reduction

**Comment by zysNLP** [comment]
@feiyuchen7 @yuchenlin PCA seems a bad method for reducing dimension. I heard a way to fix it. They say we can connect a dense neural network after the last layer.But I still can't realize it. Maybe I still not understand the BERT construction.If you fix it use this way, please tell me~

**Comment by t-kong** [comment]
Hi , Have you got the solution ?  @feiyuchen7 @shilan910 @zysNLP 
I just do as @hanxiao  say, add a  expect num hidden layer in sentence pair classification task when pretraining, but i'm not sure the new Representation would be how much badder than the 768 one .

**Comment by gioipv** [comment]
Hi, have u got the solution ?  @feiyuchen7 @shilan910 @zysNLP @t-kong  .If you fix it use this way, please tell me~

**Comment by alphamaviwiki** [comment]
> maybe you might want do a simple PCA to do the dimension reduction

I face the same problem, when I apply PCA, my tensor [[[1.11362851 1.23428118 0.76344222 ... 0.29081804 0.66497308 0.35893506]...] becomes [0. 0. 0. ....] so I am looking for other methods to reduce the dimension or get from BERT a lower-dimensional vector.
