### ISSUE TITLE
The principle.

### ISSUE THREAD

**Issue by guotong1988** [hanxiao/bert-as-service#64]
You take the final representation of [CLS] as the sentence vector?

**Comment by hanxiao** [comment]
not exactly,

please refer to
https://github.com/hanxiao/bert-as-service/blob/master/README.md#q-what-are-the-available-pooling-strategies

https://github.com/hanxiao/bert-as-service/blob/master/README.md#q-why-not-use-the-hidden-state-of-the-first-token-as-default-strategy-ie-the-cls

and

https://github.com/hanxiao/bert-as-service/blob/master/README.md#q-why-not-use-the-hidden-state-of-the-first-token-as-default-strategy-ie-the-cls


more related to this topic can be found in FAQ


Tong Guo <notifications@github.com>于2018年11月28日 周三下午5:18写道：

**Comment by guotong1988** [comment]
Two of the three link are the same.

**Comment by hanxiao** [comment]
3rd:
https://github.com/hanxiao/bert-as-service/blob/master/README.md#q-bert-has-1224-layers-so-which-layer-are-you-talking-about


Tong Guo <notifications@github.com>于2018年11月28日 周三下午6:13写道：

**Comment by guotong1988** [comment]
Thank you.
![image](https://user-images.githubusercontent.com/4702353/49146159-83d28780-f33c-11e8-8036-522b3ed03f96.png)
All token and Include the [CLS].

**Comment by hanxiao** [comment]
FYI, I made a visualization of different BERT layers, may help you understand the pool_layer and pool_strategy. See: https://github.com/hanxiao/bert-as-service#q-so-which-layer-and-which-pooling-strategy-is-the-best
