### ISSUE TITLE
Problem with CPU server

### ISSUE THREAD

**Issue by simonefrancia** [hanxiao/bert-as-service#72]
Hi, 

after last commits I am not able to use BERT CPU server anymore. I launch this command to initialize the server:
```
PATH_MODEL=`pwd`/cased_L_12_H_768_A_12/
docker build -t bert-as-service -f ./docker/Dockerfile_cpu .
docker run --runtime nvidia -it -p 5555:5555 -v $PATH_MODEL:/model -t bert-as-service
```

When I try to send request from a different machine in the LAN:
```
from service.client import BertClient
bc = BertClient(ip='192.xxxx.xx.xx') 
```
This message comes out : 
```
you should NOT see this message multiple times! if you see it appears repeatedly, consider moving "BertClient()" out of the loop.
```
and I am not able to encode my input sentence because the server seems not to receive request, but it is listening. 

PS. I have already pulled last commit both from server and client and I am able to ping my LAN server. 

PS. 2 If it can be helpful to you, with commit ```b05a985dd6f36016090371e7751fc96f328a64c7``` I am able to do previous commands.

Thanks

**Comment by hanxiao** [comment]
hmm, I think it's because `bert-as-server` now use two ports since v1.1 I believe. And I forgot to update the docker command in `README.md` accordingly.

Make sure your docker container open two ports 5555 and 5556, e.g.
```bash
docker run --runtime nvidia -it -p 5555:5555 -p 5556:5556 -v $PATH_MODEL:/model -t bert-as-service
```
Please check if this works.

More on two ports: https://github.com/hanxiao/bert-as-service#q-why-does-the-server-need-two-ports

**Comment by simonefrancia** [comment]
Still doesn't work after your advice. Thanks

**Comment by hanxiao** [comment]
Could you copy-paste the server and client output when using docker?
Client side, please use:
```python
bc = BertClient(ip='192.xxxx.xx.xx', show_server_config=True) 
```

**Comment by simonefrancia** [comment]
Sorry, now I am very busy and I am using this commit ```b05a985dd6f36016090371e7751fc96f328a64c7``` in order to make possible a BERT fine-tuning. I cannot try that at the moment. 
When I am done, I will surely try new code, thanks.

**Comment by hanxiao** [comment]
inactive, close
