### ISSUE TITLE
"no available GPU thus back-off to CPU". How to support it?

### ISSUE THREAD

**Issue by burongjiashe** [hanxiao/bert-as-service#81]
"no available GPU thus back-off to CPU". How to support it?

**Comment by hanxiao** [comment]
no extra config needed. it supports CPU out-of-box

**Comment by burongjiashe** [comment]
My GPU is in use. I can't make it use the CPU automatically.

**Comment by hanxiao** [comment]
i think you are using pretty old master. checkout the latest master and retry.

**Comment by burongjiashe** [comment]
![image](https://user-images.githubusercontent.com/20255598/49495780-28098080-f89f-11e8-9f3c-d2911144d684.png)
It stays here and can't go on.

**Comment by hanxiao** [comment]
ok i will reopen this issue as somebody else also encounter this on cpu-only machine

**Comment by hanxiao** [comment]
#90 is closed as the reason has been found, maybe you can refer to it?

**Comment by burongjiashe** [comment]
I found the reason. Because I used "tensorflow-gpu" instead of "tensorflow".

**Comment by hanxiao** [comment]
if you encounter such problem on a CPU-only machine, please try the latest version 1.5.0 by 
```bash
pip install -U bert-serving-server bert-serving-client
```

When start the server side, remember to add a `-cpu` flag, e.g.
```
bert-serving-start -model_dir /your/model/path -cpu
```

For better performance on CPU, please give a smaller `max_batch_size`, e.g. 16, 32 as suggested in https://github.com/hanxiao/bert-as-service#q-can-i-run-the-server-side-on-cpu-only-machine

Finally, #111 was the PR for fixing this issue.
