### ISSUE TITLE
How can I get the Word Embedding?

### ISSUE THREAD

**Issue by jotline** [hanxiao/bert-as-service#86]
When I fellow the step:
```
bc = BertClient()
x = ['hey you', 'whats up?']

bc.encode(x)  # [2, 25, 768]
```
I got a vector in shape [2,768]. 
So How can I get the Word Embedding?

**Comment by hanxiao** [comment]
read again
https://github.com/hanxiao/bert-as-service#q-how-can-i-get-word-embedding-instead-of-sentence-embedding
