### ISSUE TITLE
the server seems hangs

### ISSUE THREAD

**Issue by iamadog3333** [hanxiao/bert-as-service#90]
I started a server, it seems ok.
When I run a client to encode a demo sentence, the server will log a new job, but no more output after than. The server hangs. (The server log a new job only once, when I try to run a client second time, the server has no new job logged.)
When I use ctr+z to stop the server, the linux shows segment fault.
How to debug this problem? Thank you.

 
--------------
__________________server log________________________________
usage: app.py -model_dir ./models/chinese_L-12_H-768_A-12/ -num_worker=1
                 ARG   VALUE
 gpu_memory_fraction = 0.5
      max_batch_size = 256
         max_seq_len = 25
           model_dir = ./models/chinese_L-12_H-768_A-12/
          num_worker = 1
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556

I:VENTILATOR:[ser:__i: 79]:frontend-sink ipc: ipc://tmpt7XjXt/socket
W:VENTILATOR:[ser:run:100]: only 0 GPU(s) is available, but ask for 1
I:SINK:[ser:run:230]:new job b'9be1e3dd-88f6-47c4-a51b-61b74bd6e65e#ea138d3d-ac8c-479e-ba3d-18b417fd8caa' size: 2 is registered!

--------client code -------------------
from service.client import BertClient
bc = BertClient()
print('client inited.')
x = ['hey you', 'whats up?']

print(bc.encode(x))  # [2, 25, 768]
print(bc.encode(x)[0])  # [1, 25, 768], sentence embeddings for `hey you`
print(bc.encode(x)[0][0])  # [1, 1, 768], word embedding for `[CLS]`

-----------client side log-------------------
you should NOT see this message multiple times! if you see it appears repeatedly, consider moving "BertClient()" out of the loop.
client inited.

**Comment by hanxiao** [comment]
seems related to #81 
maybe a bug on CPU-only machine

**Comment by hanxiao** [comment]
if you encounter such problem on a CPU-only machine, please try the latest version 1.5.0 by 
```bash
pip install -U bert-serving-server bert-serving-client
```

When start the server side, remember to add a `-cpu` flag, e.g.
```
bert-serving-start -model_dir /your/model/path -cpu
```

For better performance on CPU, please give a smaller `max_batch_size`, e.g. 16, 32 as suggested in https://github.com/hanxiao/bert-as-service#q-can-i-run-the-server-side-on-cpu-only-machine

Finally, #111 was the PR for fixing this issue.

**Comment by nmfisher** [comment]
I've run into the same issue with a CPU-only Docker instance. I've upgraded to 1.5.0 but no dice. 
Both the server and client are instantiated and running:

```
                ARG   VALUE
__________________________________________________
                 cpu = True
 gpu_memory_fraction = 0.5
      max_batch_size = 8
         max_seq_len = 25
           model_dir = /app/model/cased_L-12_H-768_A-12/
          num_worker = 1
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556

I:VENTILATOR:[__i:run:122]:device_map:
                worker  0 -> gpu -1
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpmleudcse
WARNING:tensorflow:Estimator's model_fn (<function model_fn_builder.<locals>.model_fn at 0x7ff9e5d5f598>) includes params argument, but params are not passed to Estimator.
2018-12-11 02:52:10.841796: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-12-11 02:52:10.855842: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: UNKNOWN ERROR (-1)
2018-12-11 02:52:10.856818: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel driver does not appear to be running on this host (76b3a55b3fff): /proc/driver/nvidia/version does not exist
2018-12-11 02:52:11.669188: W tensorflow/core/framework/allocator.cc:122] Allocation of 89075712 exceeds 10% of system memory.
I:WORKER-0:[__i:gen:312]:ready and listening!
```

```
I:VENTILATOR:[__i:run:133]:new config request   req id: 0       client: b'e991674e-68b8-4887-88fc-e4fe739d4fcd'
I:SINK:[__i:run:250]:send config        client b'e991674e-68b8-4887-88fc-e4fe739d4fcd'
server config:
                max_batch_size  =       8
                   max_seq_len  =       25
                          port  =       5555
          ventilator -> worker  =       ipc://tmplIlyWd/socket
                   num_request  =       0
                worker -> sink  =       ipc://tmpKHJTL4/socket
           server_current_time  =       2018-12-11 02:53:40.172891
                num_subprocess  =       2
             server_start_time  =       2018-12-11 02:53:06.977076
            tensorflow_version  =       1.12.0
           ventilator <-> sink  =       ipc://tmp1RPUtK/socket
                 pooling_layer  =       [-2]
                        client  =       e991674e-68b8-4887-88fc-e4fe739d4fcd
                     model_dir  =       /app/model/cased_L-12_H-768_A-12/
              pooling_strategy  =       2
                python_version  =       3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609]
                server_version  =       1.5.0
                    run_on_gpu  =       False
                      port_out  =       5556
                    num_worker  =       1
I:VENTILATOR:[__i:run:133]:new config request   req id: 0       client: b'4288bb38-18b9-477c-86b7-180568dfd4ab'
I:SINK:[__i:run:250]:send config        client b'4288bb38-18b9-477c-86b7-180568dfd4ab'
server config:
                max_batch_size  =       8
                   max_seq_len  =       25
                          port  =       5555
          ventilator -> worker  =       ipc://tmplIlyWd/socket
                   num_request  =       0
                worker -> sink  =       ipc://tmpKHJTL4/socket
           server_current_time  =       2018-12-11 02:53:40.307398
                num_subprocess  =       2
             server_start_time  =       2018-12-11 02:53:06.977076
            tensorflow_version  =       1.12.0
           ventilator <-> sink  =       ipc://tmp1RPUtK/socket
                 pooling_layer  =       [-2]
                        client  =       4288bb38-18b9-477c-86b7-180568dfd4ab
                     model_dir  =       /app/model/cased_L-12_H-768_A-12/
              pooling_strategy  =       2
                python_version  =       3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609]
                server_version  =       1.5.0
                    run_on_gpu  =       False
                      port_out  =       5556
                    num_worker  =       1
```

But when I try to encode, it looks like the server hangs:
```
I:VENTILATOR:[__i:run:147]:new encode request   req id: 1       client: b'e991674e-68b8-4887-88fc-e4fe739d4fcd'
I:SINK:[__i:run:247]:job register       size: 2 job id: b'e991674e-68b8-4887-88fc-e4fe739d4fcd#1'
I:WORKER-0:[__i:gen:316]:new job        size: 2 client: b'e991674e-68b8-4887-88fc-e4fe739d4fcd#1'
```
It just sits there and never returns. *Occasionally*, the first call to encode() will work, but never any subsequent calls.

**Comment by hanxiao** [comment]
hmm, I'm reopening this issue for now to remind me.

**Comment by nmfisher** [comment]
If I manually raise StopIteration at this line:

https://github.com/hanxiao/bert-as-service/blob/6ad68827d6c7ad1e545f0a5aaaaac9db0b24f98b/server/bert_serving/server/__init__.py#L324

I can at least guarantee a single response (though of course, nothing will work after that as the worker has exited).

Not sure if this is related to the tf.data.Dataset or the zmq worker.recv_multipart()

**Comment by nmfisher** [comment]
Disabling Dataset.prefetch() seems to fix the issue. 

https://github.com/hanxiao/bert-as-service/blob/6ad68827d6c7ad1e545f0a5aaaaac9db0b24f98b/server/bert_serving/server/__init__.py#L336

Not super familiar with the tf.data API so I'm not exactly sure what's going on, or why this only seems to be an issue on the Docker/CPU-only instance.

**Comment by hanxiao** [comment]
Thanks @nmfisher for digging the problem. I also had a vague feeling that the problem may due to the `prefetch()` but can't really tell for sure. 

I didn't test with docker container, but w/o container both CPU and GPU work fine with `prefetch()`. FYI, `prefetch()` can improve about 20% inference speed, as it overlaps the CPU time (for preparing the data) and GPU time (for model computing).

Anyway, I can at least add a argument to CLI for controlling whether to use `prefetch`.

**Comment by hanxiao** [comment]
@nmfisher Just bump to a 1.5.5, with more "multi-process friendly" BertWorker. I do think this fix is related to your problem. Please kindly `pip install -U bert-serving-server bert-serving-client` to upgrade and try. Thanks!

**Comment by hanxiao** [comment]
Is upgrading to the latest version solve the problem?

```bash
pip install -U bert-serving-server bert-serving-client
```

**Comment by hanxiao** [comment]
fyi, this issue is fixed in #155 and is available since 1.6.2, please do 
```bash
pip install -U bert-serving-server bert-serving-client
```
for the update.

**Comment by pasana** [comment]
I run into the same problem.
 
> It just sits there and never returns. 

Setting timeout for BertClients output following traceback:
```

Traceback (most recent call last):
  File "/home/nickname/paradec_lib/bertser/lib/python3.5/site-packages/bert_serving/client/__init__.py", line 206, in arg_wrapper
    return func(self, *args, **kwargs)
  File "/home/nickname/paradec_lib/bertser/lib/python3.5/site-packages/bert_serving/client/__init__.py", line 291, in encode
    r = self._recv_ndarray(req_id)
  File "/home/nickname/paradec_lib/bertser/lib/python3.5/site-packages/bert_serving/client/__init__.py", line 170, in _recv_ndarray
    request_id, response = self._recv(wait_for_req_id)
  File "/home/nickname/paradec_lib/bertser/lib/python3.5/site-packages/bert_serving/client/__init__.py", line 164, in _recv
    raise e
  File "/home/nickname/paradec_lib/bertser/lib/python3.5/site-packages/bert_serving/client/__init__.py", line 153, in _recv
    response = self.receiver.recv_multipart()
  File "/home/nickname/paradec_lib/bertser/lib/python3.5/site-packages/zmq/sugar/socket.py", line 470, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 788, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 824, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable

```

Could you point out the possible problem?

**Comment by AhmedMohamedTalaat** [comment]
![InkedScreenshot_5_LI](https://user-images.githubusercontent.com/16528112/89507572-f875ee80-d7cc-11ea-977f-b19a6104a57d.jpg)
why it takes long time when get into freeze step?
