### ISSUE TITLE
REDUCE_MEAN is calculated without "input_mask"?

### ISSUE THREAD

**Issue by nrty** [hanxiao/bert-as-service#93]
Maybe only calculate the mean of non_padding characters is more reasonable?

i.e., only calculate the mean of the top 6 characters in the following example
tokens: [CLS] 我 还 可 以 [SEP]
input_ids: 101 2769 6820 1377 809 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
input_mask: 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by hanxiao** [comment]
thanks again for pointing out this issue. I've fixed in #94 and now it's in master, specifically at here https://github.com/hanxiao/bert-as-service/blob/master/bert/extract_features.py#L66

**Comment by nrty** [comment]
nice job~
