### ISSUE TITLE
按照教程来弄的 但是完全没有反应  

### ISSUE THREAD

**Issue by kouhonglady** [hanxiao/bert-as-service#97]
![2018-12-06_161709](https://user-images.githubusercontent.com/26353454/49570953-f5c95300-f972-11e8-9552-626449e6c92f.png)
![2018-12-06_161910](https://user-images.githubusercontent.com/26353454/49570960-f6fa8000-f972-11e8-88df-65d9f5fd00c9.png)
等特别久也没有任何结果输出？？ 为啥呀 请解答一下

**Comment by hanxiao** [comment]
looks like the server never starts. please refer to #81 #90 #82

**Comment by calliwen** [comment]
> ![2018-12-06_161709](https://user-images.githubusercontent.com/26353454/49570953-f5c95300-f972-11e8-9552-626449e6c92f.png)
> ![2018-12-06_161910](https://user-images.githubusercontent.com/26353454/49570960-f6fa8000-f972-11e8-88df-65d9f5fd00c9.png)
> 等特别久也没有任何结果输出？？ 为啥呀 请解答一下

你这个是启动就有问题啊，-num_worker=1试一下，你本机 只有一块gpu。

**Comment by hanxiao** [comment]
close due to inactivity

**Comment by Jackie127** [comment]
ARG   VALUE
__________________________________________________
      max_batch_size = 256
         max_seq_len = 25
           model_dir = /Users/fangchunhua/Desktop/BERTMODEL/uncased_L-12_H-768_A-12/
          num_worker = 0
       pooling_layer = [-2]
    pooling_strategy = REDUCE_MEAN
                port = 5555
            port_out = 5556

I:VENTILATOR:[ser:__i: 78]:frontend-sink ipc: ipc:///var/folders/v3/1g6dr1wn5k305c3w7q1_rmv80000gp/T/tmpJOsKtz
W:VENTILATOR:[ser:run:100]:nvidia-smi is missing, often means no gpu found on this machine. will run service on cpu instead

>>> bc = BertClient()
connect success!
server returns the following config:
bc.encode(['First do it', 'then do it right', 'then do it better'])

跑了很久都没有跑出结果，请问这是啥原因？请问bert-as-service可以表示词的特征吗

**Comment by hanxiao** [comment]
if you encounter such problem on a CPU-only machine, please try the latest version 1.5.0 by 
```bash
pip install -U bert-serving-server bert-serving-client
```

When start the server side, remember to add a `-cpu` flag, e.g.
```
bert-serving-start -model_dir /your/model/path -cpu
```

For better performance on CPU, please give a smaller `max_batch_size`, e.g. 16, 32 as suggested in https://github.com/hanxiao/bert-as-service#q-can-i-run-the-server-side-on-cpu-only-machine
